### ISSUE TITLE
Dependency on react version 0.14.0 or up

### ISSUE THREAD

**Issue by udayb2014** [react-ga/react-ga#103]
Hi guys. Looking at the source code, it looks like nothing is truly dependent on anything added/changed after React v0.14.0. Would it be possible to change the dependency to be v0.13.0 or later? I might be missing something, so please let me know if this isn't possible.

Thanks again for this project. Cheers

**Comment by yangshun** [comment]
What's the reason for that?

**Comment by udayb2014** [comment]
I'm working on a large codebase that is still on 0.13.3, which I want to use this library with. There have been a lot of breaking changes introduced in react 0.14.x and react-router 1.0.x - which will take a very long time for me to resolve.

**Comment by yangshun** [comment]
What you can do is to fork the repo and change the `package.json` in your fork.
