### ISSUE TITLE
Set page before using modalview

### ISSUE THREAD

**Issue by amangeot** [react-ga/react-ga#106]
Hello,
is it bad practice to set page before using `modalview` ? For example:
```
  ReactGA.set({ page: '/modal/' + modalName })
  ReactGA.modalview(modalName)
```

What is the purpose of `modalview` ? Apparently it is the same as `pageview` under the hood, with an extra prefix, is it for debugging purposes ?

**Comment by yangshun** [comment]
It's simply an optional helper. Feel free to ignore it.
