### ISSUE TITLE
Do I have to initialize everytime I track event from another file?

### ISSUE THREAD

**Issue by ubaidseth** [react-ga/react-ga#107]
Quick question. I can do 

```
var ReactGA = require('react-ga')
ReactGA.event({
  category: 'User',
  action: 'Created an Account'
});
```

from a different component. However, do I need to initialize it again or will that code work? I've already initialized in index.js

**Comment by yangshun** [comment]
Assuming you're writing a single page application, you do need to initialize it again as it has been initialized upon the bootstrapping of the application (index.js as you mentioned).

**Comment by ubaidseth** [comment]
You mean I don't need to?

**Comment by yangshun** [comment]
Sorry for the typo. Fixed
