### ISSUE TITLE
How to track page load speeds?

### ISSUE THREAD

**Issue by tgoldenberg** [react-ga/react-ga#108]
When I configured my GA dashboard, I notice there is a field for page load speeds - time to interactive, DOM content loaded, etc. 

How do I access this data with the `react-ga` package? It doesn't seem to be collecting it automatically, as I assumed it would. Thanks!

**Comment by vrpruthvi** [comment]
By default, 1% of users will be automatically be tracked. To change this use:
```
ReactGA.initialize('UA-000000-01, {
  gaOptions: {
    siteSpeedSampleRate: 100
  }
});
```
