### ISSUE TITLE
Console Warning - [react-ga] gaTrackingID is required in initialize()

### ISSUE THREAD

**Issue by adamhughes86** [react-ga/react-ga#109]
Hi,

Just trying to add React-GA to my create-react-app project (it's ejected) and I'm getting a console warning come up.

I've added the following to index.js
`import ReactGA from 'react-ga';`
`ReactGA.initialize('UA-XXXXXXXX');`

And I've got some events firing later on. The warning `[react-ga] gaTrackingID is required in initialize()` comes up immediately. 

Any ideas?

**Comment by yangshun** [comment]
Can you show us more code? Doesn't seem to have anything wrong with what you have shown in the issue description

**Comment by adamhughes86** [comment]
Sorry it turns out I was being a moron. The UA code wasn't being injected properly in my production environment and I also was not pushing any page view events.
