### ISSUE TITLE
First character of category, action, and label values forced to capital

### ISSUE THREAD

**Issue by uismithing** [react-ga/react-ga#110]
When viewing events in the GA console, the value of the sent event's category, action, and label has its first character capitalized when the original value is all lower case.

ReactGA.event(
{
	 "category":"kinetictext_action",
	 "action":"animate_clicked",
	"label":"randomized_sample"
});

GA console displays the values as: "Kinetictext_aciton", "Animate_clicked", and "Randomized_sample".

**Comment by yangshun** [comment]
Set `titleCase` to `false`: https://github.com/react-ga/react-ga#reactgainitializegatrackingid-options

**Comment by uismithing** [comment]
Did not read. Apologies. Tested successfully. Thank you.
