### ISSUE TITLE
Custom title in pageview support

### ISSUE THREAD

**Issue by hatchette** [react-ga/react-ga#111]
GA supports sending an optional title field with pageview. react-ga should support it as well.

I propose optional parameter 'title' is added to ReactGA.pageview

Google's documentation regarding this.
https://developers.google.com/analytics/devguides/collection/analyticsjs/pages

**Comment by rgcalsaverini** [comment]
I've submitted a PR regarding this issue.

**Comment by SimeonC** [comment]
PR Merged and versioned.
