### ISSUE TITLE
ecommerce data not being sent

### ISSUE THREAD

**Issue by NoobSkie** [react-ga/react-ga#112]
```
import React from 'react';
import {render} from 'react-dom';
import {Provider} from 'react-redux';
import {Router, browserHistory} from 'react-router';
import { syncHistoryWithStore } from 'react-router-redux';

import routes from './routes';
import configureStore from './store/configureStore';
import initialState from './reducers/initialState';
import { API_URL } from './constants';

import ReactGA from 'react-ga';
ReactGA.initialize('UA-My-ID-2');
ReactGA.plugin.require('ecommerce', { path: '/log', debug: true });

// Google Analytics
function fireTracking() {
  ReactGA.pageview(location.pathname, location.pathname);
  ReactGA.plugin.execute('ecommerce', 'addTransaction', {
    id: 'jd38je31j',
    revenue: '3.50'
  });
}
render (
  <Provider store={store}>
    <Router history={history} routes={routes} onUpdate={() => window.scrollTo(0, 0), fireTracking} />
  </Provider>, document.getElementById('app')
);
```

Here is my basic example according to the docs this should send a purchase to GA right? I have eCommerce data enabled but nothing is being sent. I can track events but not conversions.

**Comment by jehartzog** [comment]
You should have seen the addTransaction show up in the console, but given your example that data won't actually get sent to GA.

From [GA Docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce)

> Sending Data
> 
> Finally, once you have configured all your ecommerce data in the shopping cart, you send the data to Google Analytics using the ecommerce:send command:

I've been using react-ga with the enhanced ecommerce plugin and it's been working great.

**Comment by NoobSkie** [comment]
It's so weird I've just added that but still nothing

```
import ReactGA from 'react-ga';
ReactGA.initialize('UA-myid-2');
ReactGA.plugin.require('ecommerce');

// Google Analytics
function fireTracking() {
  ReactGA.pageview(location.pathname, location.pathname);
  ReactGA.plugin.execute('ecommerce', 'addTransaction', {
    id: 'jd38je31j',
    revenue: '3.50'
  });
  ReactGA.plugin.execute('ecommerce', 'send');
}
```

This should be a correct setup to at least send example data right? @jehartzog

**Comment by PhilippSh** [comment]
@NoobSkie have you managed to solve the problem?

**Comment by posix4e** [comment]
Can we reopen this?

**Comment by PhilippSh** [comment]
Don't think there are any needs. Everything works correctly. Feel free to ask any questions

**Comment by NoobSkie** [comment]
@posix4e Checkout my answer on stack http://stackoverflow.com/questions/42804001/ecommerce-tracking-data-not-being-sent-with-react-ga/42964955#42964955

**Comment by khorolets** [comment]
For those who came here for the solution. If you have the same problem, ensure you add 

```javascript
ReactGA.plugin.require('ecommerce')
...
```

before the stuff, otherwise you would see console logs in debug that everything is working, but anything is working. 

Cheers!

**Comment by ayrosochang** [comment]
@khorolets How can I use your sample on multiple tracking?

**Comment by kingeric027** [comment]
The `ReactGA.plugin.execute('ecommerce', 'send')` and `ReactGA.plugin.execute('ecommerce', 'clear')` commands are giving me the error: "Expected 3-4 artuments but got 2".
(I am using typescript with react-ga 3.3.0)
