### ISSUE TITLE
Track UTM query string parameters

### ISSUE THREAD

**Issue by TheRobBrennan** [react-ga/react-ga#113]
Is there a way to track the query string parameters - not just to see a page view to http://mysite.com/tourdates but to track any parameters like http://mysite.com/tourdates?utm_source=bathroomwall

**Comment by maxtechera** [comment]
I am looking for this same functionality.
From what I can tell this can be achieved by extracting the query params and setting them through react-ga.
Should this be a default initialization behavior ? Like checking on initialize if campaign information is in url or on every pageView?

**Comment by SimeonC** [comment]
I don't think this is something ReactGA effects, pretty sure this would be a case of your implementation is not sending the query params along with the pageView/url.

**Comment by iztokf** [comment]
can we reopen this case please?

as you can see from my pageView debug log (screenshot below), GA request looks correct (UTM tags defined) and i can see on GA dashboard that pageView is tracked correctly but with empty/undefined Medium and Source data:

**Comment by jkjustjoshing** [comment]
I'm having the exact same issue. Confirmed the tracker is getting a path that includes the correct utm query params, but nothing is showing up in the analytics dashboard.

**Comment by remo87** [comment]
> I'm having the exact same issue. Confirmed the tracker is getting a path that includes the correct utm query params, but nothing is showing up in the analytics dashboard.

Is this the expected behavior? Does the information shows in a specific report in GA?

@jkjustjoshing is it working for you?

**Comment by gsogol** [comment]
Seems like utm parameters are not automatically captured. Double checked everything. They should show up under campaigns. Anyone have any suggestions? 🙏

**Comment by ParallelUniv3rse** [comment]
For anyone still bumping into this thread, the problem for us was setting `location` via the 'set' command before a pageview. 

```
ReactGA.set({
        location: window.location.origin,
        page: window.location.pathname + window.location.search,
})
ReactGA.pageview(window.location.pathname + window.location.search)
``` 

Not setting `location` as per the info [here](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#do_not_update_the_document_location) fixed the issue.
