### ISSUE TITLE
ReactGA.OutboundLink newtab blocked in chrome

### ISSUE THREAD

**Issue by akomm** [react-ga/react-ga#118]
I encountered an issue of my target="_blank" links being blocked by chrome as a "popup".
It is caused by the navigation via JS API [at this position](https://github.com/react-ga/react-ga/blob/d86a5d4de2f8816964a000c2ea141deea2fb2420/src/components/OutboundLink.js#L22).

It does make sense to preventDefault, when you navigate away in same tab. But does it make sense to do so when the origin page remains open? The native navigation should not prevent a request to GA API in this case, because the origin tab is still open.

Luckily I'v used an own link wrapper around ReactGA.OutboundLink so the fix for all pages was easy.

The following:
```js
import React, { PropTypes } from 'react';
import ReactGA from 'react-ga';

const OutLink = ({ children, to, label, ...restProps }) => {
  return (
    <ReactGA.OutboundLink {...restProps} eventLabel={label} to={to} target="_blank">{children}</ReactGA.OutboundLink>
  );
};

OutLink.propTypes = {
  to: PropTypes.string.isRequired,
  label: PropTypes.string.isRequired
};

export default OutLink;
```
changes to this:
```js
import React, { PropTypes } from 'react';
import ReactGA from 'react-ga';

const handleOutbound = (eventLabel) => {
  ReactGA.event({
    category: 'Outbound',
    action: 'click',
    label: eventLabel
  });
};

const OutLink = ({ children, to, label, ...restProps }) => {
  return (
    <a {...restProps} href={to} target="_blank" onClick={() => handleOutbound(label)}>{children}</a>
  );
};

OutLink.propTypes = {
  to: PropTypes.string.isRequired,
  label: PropTypes.string.isRequired
};

export default OutLink;
```

**Comment by damiansilbergleithcunniff** [comment]
This worked for me.

**Comment by SimeonC** [comment]
Should be fixed now. Closing.
