### ISSUE TITLE
Please update your library to prepare for ReactJS 16

### ISSUE THREAD

**Issue by mschipperheyn** [react-ga/react-ga#121]
React.createClass is deprecated

**Comment by mbrakken** [comment]
PR https://github.com/react-ga/react-ga/pull/119 submitted for this issue.

**Comment by yangshun** [comment]
react-ga@2.2.0 published

**Comment by martinop** [comment]
I'm getting this error and  `Accessing PropTypes via the main React package is deprecated...`
