### ISSUE TITLE
warnings when calling 'timing' with 0 as a value.

### ISSUE THREAD

**Issue by polco** [react-ga/react-ga#123]
```[react-ga] args.category, args.variable AND args.value are required in timing() AND args.value has to be a number```

the type checking ```!args.value``` will return false if the value is '0'. Using hasOwnProperty would fix it.

**Comment by yangshun** [comment]
@polco Would you like to submit a PR to fix this?

**Comment by Flavien-Pensato** [comment]
The warning came back. Is is on purpose ?

**Comment by willhay** [comment]
Having this issue as well, setting args.value to 0.0000001 if the duration is 0 as a fix right now...

**Comment by stclairdaniel** [comment]
I am still having this issue. I see this fix was merged years ago but looks like something caused it to come back.
