### ISSUE TITLE
Default example for pageview in README should be updated

### ISSUE THREAD

**Issue by pencilcheck** [react-ga/react-ga#131]
GA also track query strings, so the default example in README would not work.

All you need to change is to add window.location.search to the end of pathname then it is solved

Change into
```
function logPageView() {
  ReactGA.set({ page: window.location.pathname+window.location.search });
  ReactGA.pageview(window.location.pathname+window.location.search);
}
```

Ref: [link](http://stackoverflow.com/questions/19889734/javascript-get-location-pathname-location-search-not-taking-all-parts)

**Comment by yangshun** [comment]
Would you like to submit a PR for this?

**Comment by SimeonC** [comment]
Closing as fixed in PR.
