### ISSUE TITLE
Support on Google optimize

### ISSUE THREAD

**Issue by 199911** [react-ga/react-ga#135]
The documentation does not mention [Google Optimize](https://www.google.com/analytics/optimize/).
Does the library support it?

**Comment by paschalidi** [comment]
I would also like to know if google optimize is being supported :) Also can contribute to that if needed

**Comment by paschalidi** [comment]
@199911 did you find out yourself ?

**Comment by 199911** [comment]
I read the documentation
AB test in google optimize seems require user to add a short inline script.
I don't know how to handle it in component aspect

**Comment by SimeonC** [comment]
As I posted in #141, does support of Google Optimize require anything beyond using this https://github.com/react-ga/react-ga#reactgapluginrequirename-options?
Docs I was reading for this is: https://support.google.com/360suite/optimize/answer/6262084#example-combined-snippet

**Comment by jliebrand** [comment]
Quick question that SimeonC. I managed to get Google Optimize to work by simply using:
ReactGA.ga('require', 'my-id');

What would the benefit be of using the ReactGA.plugin.require(...) api?

And would you know if either of those forces the Google Optimize script to get loaded *each* time? More specifically, I have two separate modules in my codebase, each which do:

import ReactGA from 'react-ga';
ReactGA.initialize('my-ga-tracker');
ReactGA.ga('require', 'my-google-optimize-id');

Should both modules call the require? Or just one/the first loaded?

**Comment by SimeonC** [comment]
It's equivalent, just with some checks. `ReactGA.ga('require', name, options);` is the same as `ReactGa.plugin.require(name, options);`. (There's extra debugging and checking involved: https://github.com/react-ga/react-ga/blob/master/src/index.js#L362-L405)

As for your other question, I don't think it does load both times as the original `ga` code will only load one instance (window.ga) so I think only one plugin will be required.
