### ISSUE TITLE
Test on development env

### ISSUE THREAD

**Issue by karenbajador** [react-ga/react-ga#136]
Does ReactGA only works in production? I've added the snippet into my code and enabled debug so that I can see the routes printed in the console but I do not see data coming in through google analytics. Is there a way to make it work in development?

**Comment by Pizdetss** [comment]
It's working fine for me in development. 
Are you seeing active users when you are looking at the analytics?

**Comment by karenbajador** [comment]
Nope, doesn't register anything. 
Below is my code:

![image](https://cloud.githubusercontent.com/assets/2060715/26769513/ea2315da-49f2-11e7-9860-067af7220096.png)

![image](https://cloud.githubusercontent.com/assets/2060715/26769526/ff046710-49f2-11e7-8b46-12d856c0545a.png)

Displays below on console:
![image](https://cloud.githubusercontent.com/assets/2060715/26769580/63e4ef6a-49f3-11e7-9fb1-9142859f68ba.png)


But do not see any changes on GA dashboard.
I might have been missing something.

**Comment by Pizdetss** [comment]
This may be stupid question but you don't have adblock on your browser running? 

There must be something blocking connection to GA if you aren't seeing any active users. You behind any corporate firewall?

**Comment by Mashadim** [comment]
@Pizdetss I'm having the exact same issue. I initially it slightly different but it should work. GA does say that a user is on the site but doesnt show which page view they go to.
```
ReactGA.initialize('UA-XXXX', {
  'cookieDomain': 'auto',
  'debug': true
});
```

**Comment by Pizdetss** [comment]
@Mashadim @karanjthakkar 
Sorry i'm unable to be of any further assistance as i'm just using this component on a single page application and not using routes.

**Comment by SimeonC** [comment]
There is nothing in the library that will prevent it from working on dev environments. I'd recommend you enable the chrome extension for GA debugging and see what that tells you about the setup; https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en.

**Comment by antoniwan** [comment]
Hello!

I'm having the same issue on my development environment. The Google Tag Assistant says "No tags found." and Google Analytics is not showing any real-time usage.

I'm initializing the library like this:

```
// ...
import ReactGA from 'react-ga';

ReactGA.initialize('UA-87699683-3', {
  debug: true,
});

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
```

And my router looks very similar to the example.

**Comment by SimeonC** [comment]
Hi @antoniwan, can you confirm you are using v2.2.0 or react-ga. Also which version of ReactRouter are you using?

Some of these steps may help us figure out what's going wrong;
1. `console.log(ReactGA.ga())` - this should dump out the `ga` function created by google analytics.
2. Try add `logPageView()` (from the example) when you construct/mount your router, with React Router and other routing libraries I've often found that it won't trigger the first page view as an update. Google Analytics won't show up any real time usage until the first page view from memory.
3. Just for sanity sake (this shouldn't change anything) try remove the debug line and see if your logging works after that.

**Comment by antoniwan** [comment]
Thanks for your help @SimeonC!

Yes, I can confirm the following:

1. `console.log(ReactGA.ga())` was properly dumping the GA function created by google analytics.
2. ReactGA was adding the <script> tag with the Google Analytics code into my index html file.
3. used react-ga version: `"react-ga": "^2.2.0",`
4. and react-router's version: `"react-router-dom": "^4.1.1",`
5. tried with and without the debug line and nothing happened.

I will post a more in-depth response as soon as possible.

**Comment by kklw** [comment]
Off your VPN

**Comment by MahbbRah** [comment]
So there is just no one to say something's about setting things are up on local development server for googly analytics?

**Comment by yuzhakovvv** [comment]
For me, it was a `Disconnect` Chrome Extension. After it was disabled for my local dev page and statistic period in GA was set to `Today`, I was able to see GA results.

**Comment by MahbbRah** [comment]
I didn't understand what did you want to say. Please clarify. @yuzhakovvv

**Comment by SimeonC** [comment]
Possibly the comment I left in https://github.com/react-ga/react-ga/issues/179#issuecomment-341883245 will help. I'll look into whether there is a better solution when I have more time.

**Comment by SimeonC** [comment]
In the latest release we've added the ability for turning on "testMode". I think that combined with the information in this issue should be enough to resolve most problems.

**Comment by ArshZilpe** [comment]
> This may be stupid question but you don't have adblock on your browser running?
> 
> There must be something blocking connection to GA if you aren't seeing any active users. You behind any corporate firewall?

LMAO I spent hours trying to fix the code and it was just my adblock. Thank you!
