### ISSUE TITLE
User input value

### ISSUE THREAD

**Issue by Pizdetss** [react-ga/react-ga#137]
Just wanted to check. 
The ReactGA.event ({value}) is not tracking the value inputed by the user, but more so how many times a value has been entered? Is that correct?
I'm just trying to get what a user has inputed in the field but it just fires off a number.

**Comment by SimeonC** [comment]
The problem here is that the event `value` has to be a number. See here for what each can be: https://developers.google.com/analytics/devguides/collection/analyticsjs/events. All the event function does is pass through params to that GA endpoint.

**Comment by SimeonC** [comment]
Have a look at: https://developers.google.com/analytics/devguides/collection/analyticsjs/events.
Value has to be an integer type, as I understand it the events api isn't supposed to be used that granularly. What are you trying to achieve? You can probably get the result you want without having to track that far down.

**Comment by Pizdetss** [comment]
Yep thanks for that. Issue was the value coming out wasn't a number but a string.

**Comment by SimeonC** [comment]
Closing as resolved.
