### ISSUE TITLE
Chrome Extension not sending data

### ISSUE THREAD

**Issue by JacobCooley** [react-ga/react-ga#138]
So I'm using this in my react chrome extension and it doesn't seem to be sending the data from the extension.  I thought I set something up wrong, but when I run the app in the browser it connects find.  I added this policy in my manifest file:
`"content_security_policy": "script-src 'self' 'unsafe-eval' https://ssl.google-analytics.com https://apis.google.com; object-src 'self'",
`
I have also tried using  https://www.google-analytics.com in my security policy as well

I am not receiving any errors and I couldn't find anything in my search for it.  Does anyone have any input?

**Comment by SimeonC** [comment]
From here: https://developer.chrome.com/extensions/tut_analytics you have to modify the ga code to load a different URL. Currently we don't support this so to workaround you should use the code from that link and manually run the `initialize` function here: https://github.com/react-ga/react-ga/blob/master/src/index.js#L27.

**Comment by SimeonC** [comment]
Closing as I believe creating a fix for this edge case is outside this packages scope and there is a workaround as posted above.

**Comment by mcanzerini** [comment]
Hi. I'm having the same issue. I'm trying to use react-ga for my react chrome extension.
I read that link : https://developer.chrome.com/extensions/tut_analytics but I don't understand exactly what i have to do to load ga code from a different URL. Can you provide more information ?
Thank you !

**Comment by Petemir** [comment]
@mcanzerini the previous comment references and [old version](https://github.com/react-ga/react-ga/blob/76df043082c7cf156e1a72cfa0e9c95ec26be190/src/index.js#L27) of the file. I believe now you can set the URL where you get the plugin with (https://github.com/react-ga/react-ga#reactgainitializegatrackingid-options)[options.gaAddress].

**Comment by wahlforss** [comment]
I can't get the chrome extension tracking to work...

**Comment by velchevski** [comment]
I've successfully set an SSL url using `options.gaAddress`. No errors are appearing in the console. `debug: true` shows that events and pageviews are sent, however Google Analytics doesn't register any hits. Any reason why this is happening? Could it be React-Router somehow preventing events from going through? I doubt it, as I'm sending pageviews whenever a view mounts...

**Comment by wonderbeyond** [comment]
The similar effect as @velchevski 
Got the https url loaded, but not sending data.

**Comment by wonderbeyond** [comment]
I found the solution: https://www.shanebart.com/chrome-ext-analytics/

**Comment by nahtnam** [comment]
For future reference, following the guide linked above, all I had to do was add `ReactGA.ga('set', 'checkProtocolTask', () => {});` right after the initialization
