### ISSUE TITLE
README example redundant?

### ISSUE THREAD

**Issue by ffxsam** [react-ga/react-ga#139]
```js
function logPageView() {
  ReactGA.set({ page: window.location.pathname + window.location.search });
  ReactGA.pageview(window.location.pathname + window.location.search);
}
```

Just wondering, isn't this redundant? Why would one need to set the page equal to `window.location.pathname + window.location.search` and then execute `.pageview()` on the very same string? Is this not sufficient?

```js
function logPageView() {
  ReactGA.pageview(window.location.pathname + window.location.search);
}
```

**Comment by SimeonC** [comment]
You're correct that some of it is redundant, but it's actually the other way around, see [here (link)](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications).

But the way ReactGA is coded means this won't work, if we had a SPA flag we could use your second example to automatically do the `set` step which would be cleaner. Setting that as the default wouldn't be good as ReactGA is not only for SPA apps.

**Comment by ffxsam** [comment]
Ok. It sort of makes sense. Just to clarify, in a React SPA, one must call both `set` followed by `pageview`, correct?

**Comment by SimeonC** [comment]
Yes that's correct. The link in my previous comment is to the Google docs for SPA that state as such.

**Comment by SimeonC** [comment]
Closing as resolved.
