### ISSUE TITLE
Missing Tracking Code

### ISSUE THREAD

**Issue by talbenbasat** [react-ga/react-ga#143]
Hi,

I'm using the package in my  site: www.neshama.net
Google always notifies me: Missing Tracking Code

"Make sure your pages are tagged with a supported version of the tracking code"

```
// Google analytics
const ReactGA = require('react-ga');

  ReactGA.set({ page: window.location.pathname });
  ReactGA.pageview(window.location.pathname);
```
The pageview is called onUpdate of react-router

Any idea?

**Comment by akomm** [comment]
Why not just follow the first page you see when you open this repository? The readme:

https://github.com/react-ga/react-ga#with-npm

It should fix your issue.

**Comment by SimeonC** [comment]
After a quick google this is explained here: https://support.google.com/analytics/answer/7030884?hl=en#tracking-code.

ReactGA is technically a custom implementation of the tracking code so it will give you that notification. As long as your pageviews are still going through I wouldn't worry about it.
