### ISSUE TITLE
Why cannot I send emails?

### ISSUE THREAD

**Issue by basharov** [react-ga/react-ga#144]
I want to track an event with label field containing a email string.

I see this `This arg looks like an email address, redacting.` and as a result, email doesn't go through.

Why does it happen like so and can I workaround it?

**Comment by akomm** [comment]
This sounds like a GA thing. Maybe GA itself does not accept strings with url/email to prevent spam. I would try to google GA for this issue and maybe you can configure this behavior via GA account.

**Comment by SimeonC** [comment]
Closing as this isn't related to ReactGA. Try asking StackOverflow if you can't find an answer as @akomm suggested.

**Comment by andybryant** [comment]
It's ReactGA doing this, not GA.
See https://github.com/react-ga/react-ga/blob/master/src/utils/format.js

It currently cannot be turned off. At the very least this should be a flag - it's prevents me sending stacktrace details in preferred format (with no emails) to GA.

**Comment by zyzski** [comment]
agree with above

**Comment by hilezi** [comment]
hi

since the last comment is 2018, did 2019 any update?

**Comment by zyzski** [comment]
> hi
> 
> since the last comment is 2018, did 2019 any update?

ended up forking it and making the change there to suit my needs

**Comment by hilezi** [comment]
I submit a PR(#402) for this 

may @SimeonC you can help me to review

**Comment by stevez86** [comment]
Running into this issue. The detection for an email is simply having the '@' sympbol in the string which is pretty poor. I'm removing the '@' symbol from the string.
