### ISSUE TITLE
Support for social interactions

### ISSUE THREAD

**Issue by mattfysh** [react-ga/react-ga#146]
First of all - great library!

Noticed GA has explicit support for social interaction tracking: https://developers.google.com/analytics/devguides/collection/analyticsjs/social-interactions

Is this something easily added? thanks!

**Comment by SimeonC** [comment]
Currently you can use the `ReactGA.send` function to do this (as below). If you want to specifically add support for a `social` convenience method with validation you can make a PR for it, you could look at modalView for inspiration: https://github.com/react-ga/react-ga/blob/master/src/index.js#L187-L218

```js
ReactGA.send({
  hitType: 'social',
  socialNetwork: 'Facebook',
  socialAction: 'like',
  socialTarget: 'http://myownpersonaldomain.com'
});
```
