### ISSUE TITLE
Get anayltics.js connection refused

### ISSUE THREAD

**Issue by bestestlist** [react-ga/react-ga#148]
I'm using ruby on rails for backend. Running this in localhost for testing now. But i'm getting a connection refused error in the chrome console.

GET https://www.google-analytics.com/analytics.js net::ERR_CONNECTION_REFUSED

Referrer Policy: unsafe-url

```js
    const ua = "UA-XXXXXXXX-X";
    ReactGA.initialize(ua, 'none', { debug: true });
    ReactGA.event({
      category: 'xxx',
      action: 'xxx',
      label: 'xxx',
      value: 1
    });
```

**Comment by SimeonC** [comment]
(I've removed your GA ID from your description).

I don't think this is an issue with ReactGA, can you try two things:
1. Try loading the script as shown in Google Analytics (Without using ReactGA) and see if that works. This will tell us whether it's ReactGA or your GA settings.
2. If it does work can you post the GA snippet - but remove your actual UA code as I did in your original issue.
