### ISSUE TITLE
Force loading analytics.js over https

### ISSUE THREAD

**Issue by cadecairos** [react-ga/react-ga#15]
It makes CSP easier, and there's no reason to use http over https anyways

**Comment by adamlofting** [comment]
Good call, thanks @cadecairos

**Comment by bbnnt** [comment]
useful too if used in some electron's apps

**Comment by dmitry** [comment]
Hey guys, do you mean this line: https://github.com/mozilla/react-ga/blame/master/src/index.js#L106 ?

**Comment by bbnnt** [comment]
@dmitry I guess it is

**Comment by cadecairos** [comment]
Yup that's the place that I was referring to.

**Comment by dmitry** [comment]
Looks like @cadecairos`s PR is here: https://github.com/mozilla/react-ga/pull/16

I believe it should provide possibility to choose the schema.

**Comment by jaulz** [comment]
Any information when this will be integrated?

**Comment by yangshun** [comment]
Closed via https://github.com/react-ga/react-ga/commit/8253062c2179be7b4cc156c3cccc124866212609
