### ISSUE TITLE
pageview on initialise 

### ISSUE THREAD

**Issue by tzapu** [react-ga/react-ga#153]
hello and thanks for this.
on `initialise` do we need to send an explicit pageview for root as well or is it tracked automatically by google on `initialise`

cheers

**Comment by kylecombes** [comment]
I believe so. I just set this up yesterday and had to do that to get it working. It would be nice if it were an option in the `initialize(...)` method (or at least better documentation indicating triggering it manually is required).

**Comment by SimeonC** [comment]
Yes, as @kylecombes says you need to manually send the page view. Open for PRs to add the option.
