### ISSUE TITLE
Request for an unset User ID feature

### ISSUE THREAD

**Issue by rishantagarwal** [react-ga/react-ga#154]
Hi, thanks for creating this amazing library. Awesome work guys !
 I wanted to request an unset feature for User ID for this library, because i think in some cases it would be required to do so.

**Comment by SimeonC** [comment]
Hi @rishantagarwal. How would you do this in vanilla analytics?

I don't quite understand what you are trying to do here.

**Comment by hammadzz** [comment]
@SimeonC The user has logged out. I am trying to figure out how to remove the User ID as well.

https://support.google.com/tagmanager/answer/4565987

Should we reinitialize `ReactGA.initialize()` on logout? But will that set another tracker and result in double tracking which is even worse.

**Comment by SimeonC** [comment]
I think here you'll just have to use whatever code is normally used to remove the User ID feature as this gets stored in GA not in ReactGA (we just pass it through in the initialize function). You can access the raw ga call via `ReactGA.ga(...` which is equivalent to sending a `window.ga(...`.

**Comment by damianobarbati** [comment]
@hammadzz how did you solve this? I have the same scenario: user signs out from the app.
How do I clear the userId I previously set?

**Comment by wswoodruff** [comment]
I've been using `setValue('userId', null);` to unset jt
