### ISSUE TITLE
Module parse failed: /path_to_project/node_modules/_react-ga@2.3.0@react-ga/src/index.js Unexpected token (260:71)

### ISSUE THREAD

**Issue by xxd3vin** [react-ga/react-ga#162]
I can confirm v2.2.0 is correct.

```
ERROR in ./~/_react-ga@2.3.0@react-ga/src/index.js
Module parse failed: /disk100/sscweb/workspace/SSC/ENV_PROD/fc_dotest/node_modules/_react-ga@2.3.0@react-ga/src/index.js Unexpected token (260:71)
You may need an appropriate loader to handle this file type.
|    * @param {Array} trackerNames - (optional) a list of extra trackers to run the command on
|    */
|   event: ({ category, action, label, value, nonInteraction, transport, ...args } = {}, trackerNames) => {
|     if (typeof ga === 'function') {
|       // Simple Validation
 @ ./src/home_index.js 13:15-34
 @ multi babel-polyfill ./src/home_index
```

Update:

My current solution is using `react-ga@2.2.0`

```json
{
  "dependencies": {
    "react-ga": "2.2.0"
  }
}
```

**Comment by brickfungus** [comment]
We're getting this too.  Doesn't happen with 2.2.0

ERROR in ./node_modules/react-ga/src/index.js
Module parse failed: /opt/atlassian/pipelines/agent/build/flex-view/node_modules/react-ga/src/index.js Unexpected token (260:71)
You may need an appropriate loader to handle this file type.
|    * @param {Array} trackerNames - (optional) a list of extra trackers to run the command on
|    */
|   event: ({ category, action, label, value, nonInteraction, transport, ...args } = {}, trackerNames) => {
|     if (typeof ga === 'function') {
|       // Simple Validation
 @ ./assets/src/util/GoogleAnalytics.js 15:15-34

**Comment by mcrawshaw** [comment]
Same, maybe rollback @SimeonC?

**Comment by nsarafa** [comment]
Same issue here.

**Comment by SimeonC** [comment]
Ah, crud. Sorry guys I'll get this fixed asap. It should be `"main": "dist/index.js"` not  `"main": "src/index.js"` (and this is probably in the bower as well).

The src is now using ES6 code which is the reason for the errors.

**Comment by SimeonC** [comment]
I've published 2.3.1 to npmjs, it should be fixed now. Sorry for the bother!

**Comment by karanjthakkar** [comment]
I literallty just installed 2.3.0 and faced this issue. Thanks for the quick fix, @SimeonC 💣

**Comment by mcrawshaw** [comment]
@SimeonC, thanks for the quick fix and new features!!
