### ISSUE TITLE
Events not being sent

### ISSUE THREAD

**Issue by clopes-ventureoak** [react-ga/react-ga#168]
Hey! After upgrading to 2.3.3 my events are not being send by GA... can you help?
With the debug option set everything seems to be working, but the request is not being done. And if the event is triggered with window.ga it also works.

**Comment by cheton** [comment]
Same as 2.3.4. So I downgraded react-ga to 2.2.0 as a temporary workaround.

**Comment by emilbryggare** [comment]
Same for me. Downgrade to 2.2.0 resolved the issue for now.

**Comment by nodkz** [comment]
@SimeonC I have the same problem with 2.3.4. 
Works only first pageview.
All further pageviews, events are displayed in console with `debug: true` correctly, but did not make real network requests to `/collect`.

**Comment by SimeonC** [comment]
@torstenrudolf
> Hi, I just started using react-ga, so this might be some newbie problem.
>
> unless I call initialize('tracking-id') a second time (within a timeout, that has to be at least 500s delayed after the first call in my testings) pageview('/path') won't send anything to google.
>
> I'm very puzzled that I couldn't find an existing issue here. has anyone else encountered problems, that pageview()s weren't actually sent to google?

@przemdz665
>I have a similar problem. For me, pageview() sends only the first visit but console said that everything is working fine. I spent an hour to figure it out, then I downgrade react-ga to 2.2.0.

Thanks for your patience and bug reports. I'll look into this.

**Comment by SimeonC** [comment]
OK, I think I've fixed this in the PR I just submitted. Before I merge and version would someone be able to verify by installing from `npm install simeonc/react-ga#fix-ga-call-error` and let me know.

**Comment by przemdz665** [comment]
It's working for me. I checked events and page views.

**Comment by SimeonC** [comment]
Thanks for testing, v2.3.5 has been published with the fix!
