### ISSUE TITLE
ReactGA.initialize is not a function

### ISSUE THREAD

**Issue by hlodver** [react-ga/react-ga#169]
Updating to 2.3.3 broke my build. 
Usage in code:
`
const ReactGA = require('react-ga');
...
ReactGA.initialize(GAtoken);
`
Downgraded to 2.2 and it worked.

**Comment by erkarl** [comment]
Also experiencing the same issue.

**Comment by ViscountJustin** [comment]
I am seeing the same issue, went back to 2.2 and everything is fine again.

**Comment by mandy6720** [comment]
The issue is discussed at length here: https://github.com/react-ga/react-ga/issues/165

**Comment by erkarl** [comment]
Thanks for the reference @mandy6720
