### ISSUE TITLE
Add GA's exception tracking options

### ISSUE THREAD

**Issue by adamlofting** [react-ga/react-ga#17]
I think we'll have plenty of use for these in the near term.

https://developers.google.com/analytics/devguides/collection/analyticsjs/exceptions

**Comment by hartmamt** [comment]
Any luck with this?

**Comment by yangshun** [comment]
@impronunciable can this be closed via https://github.com/react-ga/react-ga/pull/42?

**Comment by impronunciable** [comment]
Yss!
