### ISSUE TITLE
need to call `initialize()` twice before `pageview` commands get send

### ISSUE THREAD

**Issue by torstenrudolf** [react-ga/react-ga#172]
Hi, I just started using react-ga, so this might be some newbie problem.

unless I call `initialize('tracking-id')` a second time (within a timeout, that has to be at least 500s delayed after the first call in my testings) `pageview('/path')` won't send anything to google.

I'm very puzzled that I couldn't find an existing issue here. has anyone else encountered problems, that `pageview()`s weren't actually sent to google?

**Comment by torstenrudolf** [comment]
this is probably a duplicate of #168

**Comment by przemdz665** [comment]
I have a similar problem. For me, `pageview()` sends only the first visit but console said that everything is working fine. I spent an hour to figure it out, then I downgrade react-ga to 2.2.0.

**Comment by SimeonC** [comment]
Yea, I think the root cause of this is the same as #168. I'll close this thread and track the issues in that (and copy your information over). Thanks for the report.
