### ISSUE TITLE
var ga = require('react-ga'); has error

### ISSUE THREAD

**Issue by DerekHung** [react-ga/react-ga#173]
As document saying: 

```javascript
...
var ReactGA = require('react-ga');
ReactGA.initialize('UA-000000-01');
...
```

before latest update, it works fine.
but in 2.3.4(or near version) will cause below error

`TypeError: ga.initialize is not a function`

It must be changed to this: 

```javascript
...
var ReactGA = require('react-ga').default;
ReactGA.initialize('UA-000000-01');
...
```

But when I tried to reproduce this error by testing it
It pass. (So maybe something wrong with the dist file)

**Comment by SimeonC** [comment]
Thanks for pointing this out, on inspection there does seem to be something wrong with the babel/webpack process that is trying to export all the functions _before_ they are initialized.

**Comment by SimeonC** [comment]
OK, I think I've fixed this in the PR I just submitted. Before I merge and version could you verify by installing from `npm install simeonc/react-ga#fix-ga-call-error` and let me know.
I've tried it locally in nodejs and it seemed to work,  I just want someone to double check for me!

**Comment by DerekHung** [comment]
It works great !
Thank you for fixing it :D

**Comment by SimeonC** [comment]
Thanks for testing, v2.3.5 has been published with the fix!
