### ISSUE TITLE
Update outdated usage documentation with react-router >= v4

### ISSUE THREAD

**Issue by sylv3r** [react-ga/react-ga#176]
The documentation suggests to hook into the `onUpdate` function on the `Router`, however this property has been removed from `react-router` v4 and one is supposed to subscribe to router events instead.

There is a dedicated discussion in an issue of the `react-router` repository here : https://github.com/ReactTraining/react-router/issues/4278

Could you update your documentation accordingly, since this is very confusing on how to use your module at first since it doesn't work and needs some time and Google searches before figuring it out.

I'll try to propose an update with a pull request in the way I see it, but I think you should be the ones suggesting the best way to implement it.

Thanks

**Comment by SimeonC** [comment]
Have updated the Readme - there is a thread here about it too buried somewhere but I moved example usages to the Wiki and added a link from the readme.
