### ISSUE TITLE
PageView not always being sent to GA

### ISSUE THREAD

**Issue by smattt** [react-ga/react-ga#189]
I've been using react-ga for a while, when I first set it up everything appeared to be working fine but over time it seems to have degraded. Now, my pageview() calls only result in an actual /r/collect request maybe 10% of the time. I can see pageview() getting hit and the debug output seems normal - just no GA request is sent. I've tried 2.2.0, 2.3.4, and 2.3.5 but they all had the same behavior. I noticed that the calls that do occur usually result in a 302 response - could that be related? Does react-ga expect a 200 response?

I'm using react-router and hook in via onRouterUpdate to trigger the pageviews.

Here's a summary of the relevant code:

```
ReactGA.initialize(trackingId);
...
const onRouterUpdate = (): void => {
    window.scrollTo(0, 0);

    // Record the page transition in Google Analytics
    ReactGA.pageview(window.location.pathname);
};
```

This is what the debug output looks like for a typical pageview():

```
[react-ga] called ga('send', 'pageview', path);
react-ga.js:881 [react-ga] with path: /start/getStarted
```

Everything appears normal, but no request is ever made to GA. I've tried Chrome and Edge, disabled ad blocking software, tried monitoring with Fiddler and Chrome's network tool, etc.

Any help would be appreciated.

Thanks!

**Comment by designbyadrian** [comment]
I'm having the same issue. I have the Google Analytics Debug plugin, which doesn't seem to complain, but I get zero hits on analytics.google.com.

I'm initializing ReactGA in a root component, then again in components that should send events. Is that a wrong way to use ReactGA?

**Comment by smattt** [comment]
My issues were due to a misconfigured Fiddler network monitoring tool that was filtering out most image requests but not all image requests. It was allowing some GA collect calls to make it through which is what led to my confusion. It was a poorly written Fiddler filter issue, not a problem with react-ga.

Thanks
