### ISSUE TITLE
Possible issue with iframe

### ISSUE THREAD

**Issue by alantva** [react-ga/react-ga#192]
Hello.

The real-time data stopped working when I put my app to work inside an iframe to be inserted into a customer's page.
From what I've been seeing, react-ga uses the global 'window.location' which in my case will come 'blank'.
Is there any way to adapt to get the 'parent.window.location' or some other solution?

Thank you.

**Comment by SimeonC** [comment]
We only use that in the `OutboundLink` component. From the example in the readme you can just do:

```js
import ReactGA from 'react-ga';
ReactGA.initialize('UA-000000-01');
ReactGA.pageview(parent.window.location.pathname + parent.window.location.search);
```

If you need to use the `OutboundLink` component I suggest you make your own copy of it/extend the component overriding that function.
