### ISSUE TITLE
README mentions react-router but not sure how it's relevant

### ISSUE THREAD

**Issue by dminkovsky** [react-ga/react-ga#196]
In this example from the README

> Initializing GA and Tracking Pageviews with react-router:

```
import ReactGA from 'react-ga';
ReactGA.initialize('UA-000000-01');
ReactGA.pageview(window.location.pathname + window.location.search);
```

I'm not sure where react-router comes into play. Is this just a holdover from before or am I missing something?

**Comment by SimeonC** [comment]
Yes, it shouldn't have react-router mentioned there. Will remove.
