### ISSUE TITLE
React router redux middleware

### ISSUE THREAD

**Issue by saschb2b** [react-ga/react-ga#199]
I've used the linked [HOC for react router](https://github.com/react-ga/react-ga/wiki/React-Router-v4-withTracker) a while now and switched to a middleware sending all pathname and query changes as I use redux actions to change paths anyway.

https://gist.github.com/saschb2b/bff67fc8462ee106fec22207ee2638c9

Maybe this could be added to the wiki. Enhancement tips are welcome.

**Comment by SimeonC** [comment]
The wiki should be editable - feel free to add the page. Though as the comment on your gist is shown some sample usage would great as well.

**Comment by saschb2b** [comment]
@SimeonC Good call. Didn't actually think redux middleware should be explained. But for those never used one before it sure is helpfull. Will edit the wiki.
