### ISSUE TITLE
Safe to remove object-assign dependency?

### ISSUE THREAD

**Issue by benjtinsley** [react-ga/react-ga#201]
When using the react-ga package, my app gets stuck with the console error

```
Uncaught TypeError: Cannot read property '0' of undefined
```

which is traced to `/node_modules/react-ga/node_modules/object-assign/index.js`

When commenting out all react-ga related code from my app, it runs with no errors.

According to [the object-assign readme](https://github.com/sindresorhus/object-assign#use-the-built-in) it is only necessary for Node.js at less than v4. I am using Node < v8 and it appears react-ga is too, so is it possible to remove object-assign from the package.json file?

It's unfortunate that this package is the source of my trouble, but it looks like it is not needed anyway.

**Comment by SimeonC** [comment]
Closing as `object-assign` has been removed in favor of babel's `...object` syntax.
