### ISSUE TITLE
Release new version with updated typings

### ISSUE THREAD

**Issue by Vinnl** [react-ga/react-ga#204]
PR #181 exported the OutbountLink component in the TypeScript typings - great, I was just running into this!

Unfortunately, there has not been a release of react-ga since, so I can't use that right now... Any chance of cutting a new release including the updated typings? Or was there a reason for not releasing it yet that was not documented in #181 or #180? (Or anything I can do to help? :) )

/cc @SimeonC @abenchi

**Comment by SimeonC** [comment]
Just haven’t had enough time thanks to work. I have some time off next week that I plan to do the PRs and release a version at least. Sorry for the radio silence.

**Comment by Vinnl** [comment]
No problem, if there's anything I can do to lighten the burden let me know. (And thanks for maintaining this in the first place :) )

**Comment by abenchi** [comment]
Happy that I helped you 😉

**Comment by SimeonC** [comment]
Should be pushed out now.
