### ISSUE TITLE
fix the package.json "license" field

### ISSUE THREAD

**Issue by Pomax** [react-ga/react-ga#21]
it's currently set to "Apache", which is not a recognized SPDX license (for the full list, see https://spdx.org/licenses). Given that this is now hosted on a mozilla repository, we probably want this to be "MPL-2.0" instead

**Comment by adamlofting** [comment]
Good point @Pomax - and sorry for my slow reply. I don't know where my notifications for this repo have been going. :dizzy_face:

**Comment by Pomax** [comment]
no worries, I run into that more than I'd like, too =P

**Comment by yangshun** [comment]
Now that this repo has been shifted outside of Mozilla, would a `Apache-2.0` license make sense?

**Comment by yangshun** [comment]
@adamlofting could you advise on a suitable license to use for this project?

**Comment by adamlofting** [comment]
I'm no expert, but `Apache-2.0` looks fine to me.

If there's no objections, let's switch to that.
