### ISSUE TITLE
Unexpected token when setting User ID

### ISSUE THREAD

**Issue by paulballas** [react-ga/react-ga#214]
Receive error when trying to set my user id.
```
ReactGA.initialize('UA-000');
ReactGA.pageview(window.location.pathname + window.location.search);
ReactGA.set({ userId: thisUserId });
```

Error: `Syntax error: Unexpected token, expected }`

```
> 57 |         ReactGA.set({ userId: thisUserId });
     |                             ^
```

It's weird because this is no different than say `this.setState({ foo: bar })`;

**Comment by SimeonC** [comment]
That doesn't look like a ReactGA problem, I could be wrong. Try playing around with different combinations of code - probably this error isn't coming directly from there.
If that fail can you setup a small project with Webpack/babel that reproduces this error and I can have a look.
