### ISSUE TITLE
Uncaught TypeError: (intermediate value)(intermediate value).ga.apply is not a function

### ISSUE THREAD

**Issue by gazpachu** [react-ga/react-ga#220]
I get this error when initialising react-ga:

```
ReactGA.initialize('UA-00000000-1', {
  debug: false,
  titleCase: false,
  gaOptions: {
    userId: ''
  }
});
```

```
react-ga.js?7abc:194 Uncaught TypeError: (intermediate value)(intermediate value).ga.apply is not a function
    at internalGa (eval at <anonymous>

return (_window = window).ga.apply(_window, arguments);
```

are we missing a semi-colon somewhere? https://stackoverflow.com/questions/42036349/uncaught-typeerror-intermediate-value-is-not-a-function
https://github.com/standard/standard/issues/373

**Comment by TimoRuetten** [comment]
We are facing the same problem. Any solution yet ?

**Comment by kisug** [comment]
@TimoRuetten Do you have any global variable named ga?
I have same problem and i solved that problem.
In my case, I have an HTML Element that id is "ga". after i change the id of element and the error is disappear.

**Comment by gazpachu** [comment]
Fixed! thx. It was the flag from Gabon! :-)

`import GA from '../assets/svg/flags/ga.svg';`

**Comment by chrisbutler** [comment]
i'm having this problem trying to `import * as ReactGa from 'react-ga'`

calling `ReactGA.ga` gives the "apply is not a function message... but it works if i call `ReactGA.default.ga`?!?
