### ISSUE TITLE
Issues no tracking 15-20% of all traffic

### ISSUE THREAD

**Issue by manelgarcia** [react-ga/react-ga#225]
Hi there!

First things first, congratulations for this great plugin.

We're facing a weird issue since we switched from PHP (analytics.js) to React (react-ga) implementation. For some reason, something like 15-20% of all traffic is not being tracked at all. 

Some days, AdWords clicks are even bigger than GA sessions.

Does anyone have an idea of what can be causing this?

We're using react-router and it's an SSR site.

Our implementation is like the following:

App.js: File which render the routes, on constructor:
```
    ReactGA.initialize('UA-XXX', {
      debug: false,
      titleCase: false,
      gaOptions: {
        userId: this.props.user.uid
      }
    });
```

And on this same file:
```
// on componentDidMount
  componentDidMount() {
    const page = this.props.location.pathname + this.props.location.search;
    ReactGA.set({ page });
    ReactGA.pageview(page);
    ReactGA.plugin.require('displayfeatures');
 }

// on componentDidUpdate
    if (prevProps.location.pathname !== this.props.location.pathname) {
      const page = this.props.location.pathname + this.props.location.search;
      ReactGA.set({ page });
      ReactGA.pageview(page);
    }
```

Is that wrong, can someone help us please?

Thanks in advance!

**Comment by SamMatthewsIsACommonName** [comment]
I'm currently looking into how to avoid being blocked by an ad blocker (which would probably explain those proprotions). Will report back when I find a good solution

**Comment by manelgarcia** [comment]
I don't know...

I've tried myself with AdBlocker and GA is not blocked, FB Ads is instead. We're going crazy with this at the office. Since then, I've tried a few things:

- I thought that maybe for some reason, because first render is always SSR, initializing in `constructor` could be breaking GA if it was a slow device, so I moved `ReactGA.initialize` from `constructor` to `componentDidMount`, no success, metrics are still nonsense.

- We have a kinda thank you page, where we save the conversion and a few things are done in there. Interesting ones are the following
  * ReactGA ecommerce event is sent
  * API POST request to our system is sent

  We've compared, in one day:
    * How many visitors, sessions and how many times event has been fired
    * How many (valid) requests our frontend received
    * How many (valid) requests the API server received
    * How many records are in the db.

  Shitty thing is that everything matches except GA, thats what led me to think that was a GA related issue. 

Unless we're making a noob implementation mistake, or god makes us pay our sins, I'm running out of ideas.

I don't believe this is code related thing with ReactGA and that we're the first ones to experience it, so I  think I'm just looking for some hope.

Thanks for your time guys and apologies for my english.

**Comment by SimeonC** [comment]
Hey, I think your setup (in short form) would be like below.
On the SSR point, it doesn't matter SSR vs In Browser as the one on SSR will be ignored (window doesn't exist on SSR) and the browser one will be fired.

If your concern is that the ecommerce events aren't being tracked but the pages are being tracked that's because you have to send a page view after your ecommerce events or they won't be tracked.
If even your page views aren't being tracked properly (and your app is like the following) you will need to move your componentDidUpdate to a wrapper around the top route as this App component won't update with route changes.
This Wiki page might help; https://github.com/react-ga/react-ga/wiki/React-Router-v4-withTracker

```js
// App.js

class App extends Component {
  constructor() {
    ReactGA.initialize();
  }
  componentDidMount() { as in your code }
  componentDidUpdate() { as in your code }
  render() {
    return (
      <ReactRouterDom>
        <Route ... />
      </ReactRouterDom>
    );
  }
}
```

**Comment by manelgarcia** [comment]
Thanks @SimeonC 

I'll try it asap.

I close due to a implementation issue, not a bug.

Thanks for your time.
