### ISSUE TITLE
How to add Site Speed Sample Rate? 

### ISSUE THREAD

**Issue by vitthalr** [react-ga/react-ga#228]
https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#siteSpeedSampleRate

Is this code correct?: -
`ReactGA.initialize('UA-000000-01', {'siteSpeedSampleRate': 100});`

I couldn't find a way to verify if this is working or not.

Also, bounce rate in GA is showing as zero (0). Will adding this help?

**Comment by vitthalr** [comment]
Any update on this?

**Comment by SimeonC** [comment]
Hey, not quite right, try the following:

```js
ReactGA.initialize('UA-000000-01', {
  gaOptions: {
    siteSpeedSampleRate: 100
  }
});
```

`options.gaOptions` is passed through to the `ga('create', ...` from the docs.
