### ISSUE TITLE
ReactGA.event sending to analytics with category first letter uppercase

### ISSUE THREAD

**Issue by santimendoza** [react-ga/react-ga#231]
I start sending events to google analytics using this package, but start seeing the category with the first letter in uppercase.

Is there something related to the package? Because before using it, I effectively send events to google analytics without the first letter in uppercase.

My code:

```
ReactGA.event({
      category: 'mycategory',
      action: 'click',
      label: 'mylabel'
    });
```

And in google analytics it appear like:

`Mycategory` and with action `Click`.

Using "react-ga": "2.4.1"

**Comment by manelgarcia** [comment]
From docs:


> options.titleCase | Boolean. Optional. Defaults to true. If set to false, strings will not be converted to title case before sending to GA.

Maybe this can help?

**Comment by santimendoza** [comment]
I was looking the documentation part about ReactGA events. Hadn't see that part.

Thanks @manelgarcia, that should work.

**Comment by andrewmclagan** [comment]
Why is this even done...?

**Comment by santimendoza** [comment]
@andrewmclagan With the titleCase option you can disable the first letter upercase. At least, it worked for me.

**Comment by santimendoza** [comment]
@andrewmclagan In my case, i needed it without titleCase because I already have data for an specific category.

The advantage about the titleCase? I think is more like "fancy". But maybe people that use it have a good reason to use it.

**Comment by SimeonC** [comment]
I don't think it's worth it to change the default - would constitute a major breaking change for the reasons you outlined. I can see how it would be problematic so we should probably add a section to the readme of differences between the defaults and vanilla ga.

Originally there was no option so I'm guessing this was the preference of the original authors https://github.com/react-ga/react-ga/issues/24

**Comment by gsamat** [comment]
Bite me in the ass just now. Need a BIG WARNING.

**Comment by glebdv** [comment]
It absolutely should be a warning, since it's not expected or even predicted behavior. However, I tested it prior to a live push and I caught the problem, which was rectified. Hence, I didn't really have a problem. I mean, if you don't test, it's a little on you.

**Comment by ilovett** [comment]
wow I'm so glad the original author changed the default to automatically title case everything.

I think it's worth a breaking change to fix it.

**Comment by sundquistm** [comment]
+1 This is essentially a bug if you're transitioning to ReactGA from a pre-existing solution.

**Comment by lilian-miakito** [comment]
This is still an issue with react-ga4 and it's still not an option unless you fork the whole thing.

**Comment by mitul-parmar-simform** [comment]
Is it achievable for React-ga4?
