### ISSUE TITLE
Error on ReactGA.event() [ReactGA is not defined]

### ISSUE THREAD

**Issue by albertoperezf** [react-ga/react-ga#232]
This happened on my prod server when I try to launch the `ReactGA.event` method. I try different things but anything seems to result. The weird thing is that the other methods of the package (initialize, pageview, set, etc) works fine.

![image](https://user-images.githubusercontent.com/7967007/37518151-45d31ca8-2914-11e8-87ac-202b9b321816.png)

![image](https://user-images.githubusercontent.com/7967007/37518067-ebe517be-2913-11e8-84af-e7a19fd4204f.png)

Any ideas?

**Comment by SimeonC** [comment]
Did you forget to import ReactGA? That on its own looks fine but it's probably somewhere else in your code. Can you post some more of the file that triggers the error? (Though I'm pretty sure this isn't ReactGA problem)

**Comment by albertoperezf** [comment]
I'm going to close this because I find another way to do it (Using ReactGA). I think the issue had to do with our Router.
