### ISSUE TITLE
gtag.js usage

### ISSUE THREAD

**Issue by GazzaHazza** [react-ga/react-ga#236]
Just wondering if possible to use along side a `gtag.js`. I can see in the docs you have a options for `initialize` you have a option of `gaAddress`, would it be possible to pass the address to `gtag.js` instead?

**Comment by SimeonC** [comment]
From what I understand no, you can’t. As gtag.js works differently from analytics.js.
Might be wrong as I’ve not had the time to look into gtag properly yet.

**Comment by GazzaHazza** [comment]
Ok thanks!
