### ISSUE TITLE
Make toTitleCase optional?

### ISSUE THREAD

**Issue by ericclemmons** [react-ga/react-ga#24]
Hi!  I was able to replace our crappy solution with `react-ga` this morning, but, while I agree about the formatting conventions, our BI reporting is based on exact label/category/event matches.

Would you be open to a PR that made this sort of thing disable-able via:

```js
ga.initialize("UA-00000-01", {
  debug: true,
  format: false,
  // or
  pretty: false,
  // or
  normalize: false,
});
```

Let me know before I work on a PR.  Thanks!

**Comment by dmitry** [comment]
Any updates here?

**Comment by adamlofting** [comment]
Hey @ericclemmons - I'm sorry for such a slow reply. I've not had my notifications set up properly for this repo and have only spotted people filing issues today :dizzy_face: 

I'm happy to have this as a configuration option. 

How about `titleCase` as the config flag? It defaults to `true`.

**Comment by yangshun** [comment]
https://github.com/react-ga/react-ga/pull/34 attempts to fix this.

**Comment by yangshun** [comment]
Have fixed this in #63. @adamlofting @impronunciable could you help publish this to NPM?

**Comment by impronunciable** [comment]
I'm out of town but try to do it asap

**Comment by impronunciable** [comment]
@yangshun Published as 1.4.1

**Comment by adamlofting** [comment]
thanks @impronunciable

**Comment by yangshun** [comment]
@adamlofting possible to give me publishing permissions?

**Comment by adamlofting** [comment]
@yangshun sure - what's your npm username?

**Comment by yangshun** [comment]
Thanks @adamlofting . It's `yangshun`: https://www.npmjs.com/~yangshun
