### ISSUE TITLE
When using multiple trackers, all hits are also sent to the default tracker even if you specify a named tracker

### ISSUE THREAD

**Issue by rvaidya** [react-ga/react-ga#242]
In my test I am creating a single named tracker, and then sending an event:  The test mode API gives me this:

```
    [ [ 'create', 'UA-XXXXXX', { name: '4yw9uzk0xcx' } ],
      [ 'send',
        { hitType: 'event',
          eventCategory: 'Jest',
          eventAction: 'send sample event' } ],
      [ '4yw9uzk0xcx.send',
        { hitType: 'event',
          eventCategory: 'Jest',
          eventAction: 'send sample event' } ] ]
```

internalGa(...args) is always called even if trackerNames is set

```
function _gaCommand(trackerNames, ...args) {
  const command = args[0];
  if (typeof internalGa === 'function') {
    if (typeof command !== 'string') {
      warn('ga command must be a string');
      return;
    }

    internalGa(...args);
    if (Array.isArray(trackerNames)) {
      trackerNames.forEach((name) => {
        internalGa(...[`${name}.${command}`].concat(args.slice(1)));
      });
    }
  }
}
```

**Comment by SimeonC** [comment]
Thanks for the report, can you include the code you are using to trigger those events.
It does look like an oversight to be sending both, though I'm not sure. The original PR for this was https://github.com/react-ga/react-ga/pull/145/files#diff-1fdf421c05c1140f6d71444ea2b27638R34. @DveMac I don't use multiple trackers, could you comment on whether this is a bug or not?

**Comment by rvaidya** [comment]
My tests are on a wrapper for analytics so i'm not calling react-ga directly in my tests.

An approximation would be something like:

`ga.initialize([ { trackingId, gaOptions: { name } } ], { testMode: false, titleCase: false });
ga.event({ category: 'Jest', action: 'send sample event' }, [ name ]);
`

**Comment by DveMac** [comment]
Hi @rvaidya, in its current form it is unavoidable because there is no way to specify the default tracker.  Right now I can not think of a backwards compatible change that would allow you to _only_ send to the specified trackers.

**Comment by DveMac** [comment]
This PR might help if you have control over ReactGA.initialize() - https://github.com/react-ga/react-ga/pull/245

**Comment by rvaidya** [comment]
Is there a use case for sending to both trackers at once?

If you put the default send in an else and don't pass the trackerNames argument, it will send to the default tracker since the if check checks to see if the argument has an array shape - I did a quick test in testMode and received calls that looked correct.

`
function _gaCommand(trackerNames, ...args) {
  const command = args[0];
  if (typeof internalGa === 'function') {
    if (typeof command !== 'string') {
      warn('ga command must be a string');
      return;
    }

    if (Array.isArray(trackerNames)) {
      trackerNames.forEach((name) => {
        internalGa(...[`${name}.${command}`].concat(args.slice(1)));
      });
    } else {
        internalGa(...args);
    }
  }
}
`

**Comment by DveMac** [comment]
> Is there a use case for sending to both trackers at once?

There definitely is, that is why I created the PR originally :)

**Comment by rvaidya** [comment]
Thanks for the PR
