### ISSUE TITLE
Custom Variables / Dimensions?

### ISSUE THREAD

**Issue by ericclemmons** [react-ga/react-ga#25]
This library doesn't readily support it yet.

Would you be open to a PR with a `.set` and a `.send` method that offers this?  Heck, `.event` would be able to utilize it as well.

> http://stackoverflow.com/questions/16440499/how-to-set-custom-variables-through-the-new-analytics-js-of-ga

**Comment by adamlofting** [comment]
This would be a great addition. Sorry for my slow reply on this ticket also! :dizzy_face: 

I'll have a look at that related PR that's been opened now. :+1:

**Comment by johnpez** [comment]
Interested in this as well, any progress on this feature?

**Comment by yangshun** [comment]
@ericclemmons @johnpez v0.1.3 now supports `ga.set({ ... })`. It may be more troublesome but custom variables / dimensions are now available by `set`-ting before `send`-ing.

**Comment by johnpez** [comment]
@yangshun Great, thank you!

**Comment by yangshun** [comment]
Closed by https://github.com/react-ga/react-ga/pull/45
