### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by kenjoe** [react-ga/react-ga#250]
Hello, I used this library in my react app (server side rendering) and I saw some error in my server when in production, it pointed in "react-ga.js" file, line 891. Error says "document is undefined".

Please help me with this, did I miss something for setup?

**Comment by kenjoe** [comment]
Update, I fixed the error by checking if document is undefined.

**Comment by kunmura** [comment]
@kenjoe Hello.  I am having the same problem.
Please tell me how to check.

**Comment by kenjoe** [comment]
Hi @kunmura I added if statement like this:

`if(typeof window !== 'undefined' && typeof document !== 'undefined') {
	// Your ReactGA initialization here..		
 }`
