### ISSUE TITLE
module react has no export default with typescript

### ISSUE THREAD

**Issue by tanphamhaiduong** [react-ga/react-ga#254]
![image](https://user-images.githubusercontent.com/22660833/39586467-532606d0-4f21-11e8-9034-73e62802c1df.png)

I think it should be import * as React from 'react'

**Comment by bcherny** [comment]
Please bump the version on NPM - 2.5 is still broken.

**Comment by SimeonC** [comment]
Sorry for the delay, pushed out 2.5.1 to NPM.

**Comment by garycourt** [comment]
I'm still not seeing [2.5.1 on NPM](https://www.npmjs.com/package/react-ga/v/2.5.1).

**Comment by SimeonC** [comment]
Sorry about that! I keep forgetting my work machine points to a private NPM repo and publishing it there 🤕 .

I published 2.5.2 properly with an extra typescript fix.
