### ISSUE TITLE
ReactGA page view added always as new session

### ISSUE THREAD

**Issue by santimendoza** [react-ga/react-ga#256]
I am using ReactGA, and seems like everytime I send a page view to analytics, it count it as a new session and not just as a pageview.

Do we have to do something in order to track sessions so we can track page views and not sessions?

**Comment by SimeonC** [comment]
That sounds like it's not related to ReactGA as we don't do anything special to do with sessions (I don't think). Try doing a search on google for that issue under `google analytics.js`. That might point you in the right direction.
