### ISSUE TITLE
testModeAPI removed from types definition by mistake ?

### ISSUE THREAD

**Issue by alanrubin** [react-ga/react-ga#262]
Hi, I'm trying to test the library in Jest and getting error "[ts] Property 'testModeAPI' does not exist on type 'typeof "/.../node_modules/react-ga/types/index"'." when trying to access the ReactGA.testModeAPI method. 

By looking at the types definition (index.d.ts) it seems the testModeAPI definition was removed a couple of months ago... Is that something that was done by mistake? Can I do a PR for it?

Cheers,
Alan

**Comment by alanrubin** [comment]
I'm using that version, indeed the interface is there but the const testModeAPI exported is not - it was removed at this commit https://github.com/react-ga/react-ga/commit/d751e25f0660442e72f9aef5358f298a52c3bf33#diff-88bec6beae84369c0376b56b3bb88fe1L81 - I guess that was unintentionally...

**Comment by SimeonC** [comment]
Ah 😢 , sorry I must have missed that in the review. If you could do a PR for it that would be a great help, then I can merge and do a patch version when I get to my work laptop tomorrow.
