### ISSUE TITLE
ReactGA is not working

### ISSUE THREAD

**Issue by PrabhanshuAttri** [react-ga/react-ga#266]
I have tried different ways to integrate Google Analytics with react-ga for an open source project ([Aha! Event](https://github.com/forksociety/AhaEvent)), but it's not working.

```
    if (!process.env.NODE_ENV || process.env.NODE_ENV === 'production') {
      let gaTrackingId = config.get('gaTrackingId')

      console.log('Environment', process.env.NODE_ENV)
      ReactGA.initialize(gaTrackingId, {
        debug: true,
        gaOptions: { cookieDomain: 'auto' }
      })
    } else {
      console.log('Environment', process.env.NODE_ENV)
    }
```

Tried this as well
```
ReactGA.initialize([{ trackingId: gaTrackingId, debug: true, gaOptions: { cookieDomain: 'auto' }}])
```

Am I am doing something wrong while implementing react-ga?

[Find complete code here](https://github.com/forksociety/AhaEvent/blob/master/src/App.js#L27)

**Comment by DveMac** [comment]
Your ReactGA initialization should not be in the render method of the react component. 

This code https://github.com/forksociety/AhaEvent/blob/master/src/App.js#L24-L30 should probably be somewhere around line 10 (in your example)

**Comment by PrabhanshuAttri** [comment]
I tried that as well.

![z](https://user-images.githubusercontent.com/4739486/40788965-ee48c88e-650e-11e8-8ab5-3eb474c0c6d3.png)


The code is deployed here http://ahaevent.org.

**Comment by DveMac** [comment]
Where in your code are you calling `ReactGA.pageview()` or `ReactGA.send()`?

**Comment by PrabhanshuAttri** [comment]
Moved the pageview code as well.
 
![z](https://user-images.githubusercontent.com/4739486/40790463-a2378670-6512-11e8-9981-1f2d8b17f27c.png)

The console shows the event triggers, but no trace of pageview on Google's dashboard or Google tag manager.

**Comment by DveMac** [comment]
It appears like you are still calling `ReactGA.initialize()` multiple times

**Comment by PrabhanshuAttri** [comment]
I have initialized it only once.
![z](https://user-images.githubusercontent.com/4739486/40792521-c43bb840-6517-11e8-99d7-8fa58c8cbd4a.png)

I can see few pages views on analytics dashboard, but not all page views are tracked. Active users stay zero.
![a](https://user-images.githubusercontent.com/4739486/40792743-4a33a214-6518-11e8-8cf8-07e93ededc11.png)

This is weird. :confused:

**Comment by PrabhanshuAttri** [comment]
It's fixed. I don't know how. I think it was partly related to improper usage (Thanks @DveMac for helping me fix that) and partly related to adblocking plugins and router restrictions. Closing this.

**Comment by RahulReddy75** [comment]
I went through the same problem and turns out that the issue was because of adblockers and third party plugins.

**Comment by arangates** [comment]
with Adblocker plugin it doesn't work

**Comment by DveMac** [comment]
Yes, some/most adblockers will block access to google analytics domain - there is nothing this library can do about that.

**Comment by codebravotech** [comment]
Same with ghostery, I forgot I had it installed and just pissed away an hour not understanding why I wasn't seeing events 🤣

**Comment by foodaka** [comment]
Wow i realized i was on Brave browser hence it wasn't tracking. Kudos to Brave for an awesome browser :)

**Comment by Pacheco95** [comment]
I have configured everithing well. The GA events are being logged to the console but the dashboard remains untouched.
I have also disabled my adblock.
Here is my example code
https://github.com/Pacheco95/smartinvest/blob/main/src/index.tsx
https://github.com/Pacheco95/smartinvest/blob/main/src/App.tsx

**Comment by BlackH3art** [comment]
I have the same issue, but I don't think it is because of ad blockers in my case. I tried 5 different browsers. 
- Chrome
- Brave
- Firefox
- Firefox developer edition
- Edge

Here is my initialization:
```javascript
ReactGA.initialize('G-4YDE9DH4RW');

function App() {
  
  useEffect(() => {
    ReactGA.pageview(window.location.pathname + window.location.search);
  });

  return (
    <Router>
      <div className="app">
        
        <Navigation />

        <ToastContainer />
        <ShowCookie />
        
        <ScrollToTop>
          <Routes>

            {/*  SOME ROUTES IN HERE */}

            <Route path="*" element={ <Navigate to="/" /> } />

          </Routes>
        </ScrollToTop>

        <Suspense fallback={<div />}>
          <Footer />
        </Suspense>
        
      </div>
    </Router>
  )
}

export default App;
```

**Comment by timakhalaya** [comment]
You need a universal tracking id 
The **ReactGA.initialize('G-4YDE9DH4RW');** will not work
It should be in a format - UA-******
