### ISSUE TITLE
Does this package support enhanced ecommerce?

### ISSUE THREAD

**Issue by bsansone** [react-ga/react-ga#269]
I was able to implement the normal [ecommerce plugin](https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce) just like how it was shown in the bottom comment by **khorolets**  in this issue https://github.com/react-ga/react-ga/issues/112 but I need to be able to access the [enhanced ecommerce plugin](https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#migration) to track things such as impressions and checkout steps, but I receive errors in my debug console such as:
```
Plugin "ecommerce" does not have method "setAction".
Error calling a plugin method: {0: "ecommerce:setAction", 1: "checkout", 2: {step: 1}}
```
when trying to follow the example [here](https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#checkout-process)

Are there additional configurations needed to be set up to be able to access those that I'm unaware of? I have enhanced ecommerce toggled on in the admin section of the view I'm working in

Using version 2.5.0 of react-ga

**Comment by hchood** [comment]
@bsansone Not sure if you figured this out already or not, but you likely need:

```js
// require the correct plugin
ReactGA.plugin.require('ec') // not 'ecommerce'

// use that plugin in your other calls, e.g.:
ReactGA.plugin.execute('ec', 'setAction', 'checkout', { step: 1 })
```

Hope that helps!

**Comment by bsansone** [comment]
Hi @hchood, I was actually able to figure this out after some troubleshooting and digging, appreciate the response!

**Comment by bsansone** [comment]
@dimanyc Here is an example of how we are tracking a "purchase" in our app.
```js
if (eventName === 'purchase') {
    for (let i = 0; i < params.lineItems.length; i++) {
        ReactGA.plugin.execute('ec', 'addProduct', {
            id: params.orderId,
            name: params.lineItems[i].name,
            sku: params.lineItems[i].sku,
            category: params.lineItems[i].category,
            price: params.lineItems[i].price,
            quantity: 1, // We only have 1 of each item, so this is a static value
            currency: params.currency,
        });
    }
    ReactGA.plugin.execute('ec', 'setAction', 'purchase', {
        id: params.orderId,
        affiliation: params.siteName,
        revenue: params.totalPrice,
        shipping: params.totalShipping,
        tax: params.totalTax,
        currency: params.currency,
    });
    ReactGA.pageview('/confirmation');
    ReactGA.plugin.execute('ec', 'clear');
}
```
We are also using [react-metrics](https://github.com/nfl/react-metrics) to pass our event params to multiple analytic vendors so they all get the same data based on which `eventName` is emitted with the data.

**Comment by dimanyc** [comment]
@bsansone awesome!

**Comment by lukepereira** [comment]
@bsansone what does `ReactGA.plugin.execute('ec', 'clear');` do? I'm not seeing it in the documentation anywhere

**Comment by bsansone** [comment]
@lukepereira It essentially clears out the data you've been executing with the plugin, so if you finish a transaction you want to use `clear` to remove all the items in the ga shopping cart.

See https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce#clearingData

**Comment by aodhol** [comment]
@hchood Is 'ec' for enhanced e-commerce only or when should 'ec' be used instead of 'ecommerce'

**Comment by hchood** [comment]
@aodhol Just enhanced ecommerce I believe.  See "Load the Ecommerce plugin" sections here:
https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce
https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#migration
