### ISSUE TITLE
window is not defined error

### ISSUE THREAD

**Issue by achhranitesh** [react-ga/react-ga#272]
Hi,

I am creating an React App using Next JS for SSR. So when added the ReactGA.initialize event is head tag for _document.js. It is throwing an error for 'window is not defined'.

A quick and prompt solution would be helpful

**Comment by DveMac** [comment]
Can you check that window exists before calling `initialize()`.

```

**Comment by romanown** [comment]
but in that case GA will not be initialized and will not work?

**Comment by DveMac** [comment]
You most probably don't want it initializing on the server anyway. It should initialize only when the code is run on the client
