### ISSUE TITLE
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

### ISSUE THREAD

**Issue by p0k8h** [react-ga/react-ga#282]
`<Route exact={true} path="/clients" component={withTracker(Clientlist)} />`

I had configured the `react-ga` as the https://github.com/react-ga/react-ga/wiki/React-Router-v4-withTracker guides.

But when I navigate to the `/#/clients` the component keeps on rendering goes on.... until the maximum calls. I guess as per the error below, state is being changed and it renders multiple times.

But doesn't know where to configure it!

![deepinscreenshot_select-area_20180809165647](https://user-images.githubusercontent.com/19905275/43895493-3e641e8c-9bf5-11e8-9558-b7f086e1a35e.png)

**Comment by parwat08** [comment]
I guess there is nothing much inside the ClientList component.
The `withTracker` component is called around more than 500 times.

I am stuck doesn't know where to debug?

**Comment by SimeonC** [comment]
If you copied the withTracker HOC from the wiki it shouldn’t be doing anything that could cause a rerender. My guess is something is changing your route or ClientList is doing something you aren’t expecting. Try removing the HOC and see if it still occurs.

**Comment by parwat08** [comment]
No, after removing the HOC it won't cause the problem.

`withTracker` is being renderred multiple times. I guess it has nothing to do with `ClientList`

routes.js
```

import { HashRouter, BrowserRouter, Route, Switch, Link, Redirect } from 'react-router-dom';

class routes extends Component {

    componentDidMount() {
        // some boolean state changes to restrict the routes
    }

    componentWillReceiveProps() {
        // some boolean state changes to restrict the routes
    }

    render() {
        return (
            <HashRouter>
                <App>
                    <Route exact={true} path="/clients" component={withTracker(Clientlist)} />
                </App>
            </HashRouter>)
    }
}

```
index.js

```
import AppRoutes from './router/routes';

ReactDOM.render(
    <Provider store={store}>
        <AppRoutes />
    </Provider>,
    document.getElementById('root'));
registerServiceWorker();

```
Any help is MUCH Appreciated. 
Thanks!

**Comment by SimeonC** [comment]
Try replicate it here, as it looks fine to me: https://codesandbox.io/s/7j1kj6xz96

**Comment by kilegalloway** [comment]
https://icetutor.com/question/reactjs-maximum-update-depth-exceeded-error/
