### ISSUE TITLE
Type Definitions have no default export

### ISSUE THREAD

**Issue by martinmckenna** [react-ga/react-ga#286]
When doing:

`import ReactGA from 'react-ga'` 

with TypeScript, the error `react-ga has no default export`

so instead you need to do something like

`import { event } from 'react-ga'`

Could you please include the default export in your type definitions?

**Comment by RetroCraft** [comment]
To import the entire TypeScript module, use `import * as ReactGA from 'react-ga'`. 

This is standard practice with a lot of libraries in my experience. It allows for things like tree-shaking in Webpack and the like.

**Comment by martinmckenna** [comment]
Ah gotcha. Thanks for quick reply.

The only piece of feedback I would say is to include this somewhere in the README instructions
