### ISSUE TITLE
How to track Page Load time?

### ISSUE THREAD

**Issue by adrianhorning** [react-ga/react-ga#288]
I just want to see how long it takes for a page to load. ReactGA is sending data, but I can't see anything in Google Analytics. 
This is the code I'm using: 
```
if (window.performance) {
    // Gets the number of milliseconds since page load
    // (and rounds the result since the value must be an integer).
    const timeSincePageLoad = Math.round(performance.now());

    // Sends the timing hit to Google Analytics.
    ReactGA.timing({
        category: 'Page Load Time',
        variable: 'load',
        value: timeSincePageLoad, // in milliseconds
        label: window.location.pathname
    });
}
```

**Comment by SimeonC** [comment]
Hey, sometimes GA can take a while to propagate especially if you hit their threshold.

Did you check it was sending using the GA debugger or do you get other events like page visits from ReactGA in GA? It looks like your code is correct to me so it might be a bug.

**Comment by adrianhorning** [comment]
Actually, I think I got it. I think you can close this. So, I had to put `gaOptions: { siteSpeedSampleRate: 100 }` when I initialized, and I think that fixed it. I needed to send up 100% of the pages, or something like that. Maybe this could be included in the documentation? I guess I could create a pr huh? I'll do that now.

**Comment by adrianhorning** [comment]
Resolved.
