### ISSUE TITLE
ReactGA.ga() doesn't log any data.

### ISSUE THREAD

**Issue by FloSugar** [react-ga/react-ga#291]
I'm trying to log a custom dimension event using `ReactGA.ga()` but no data appear in my google analtyics.

Here is my code:

```
ReactGA.ga(
  'send',
  'openEvent',
  {
  'type': 'eventPreview',
  'userId': this.props.userId, //string
  'invitingId': this.props.invitingId, //string
  })
```

I have however no problem logging a `ReactGA.event()` like so:

```
ReactGA.event({
 category: 'eventPreview',
 action: 'openEvent',
})
```

**SPECS**
```
    "react": "^16.4.0",
    "react-ga": "^2.5.3",
```

Am I doing something wrong?

**Comment by DveMac** [comment]
As far as I know `openEvent` isnt a valid hitType, the options are 

The type of hit. Must be one of 'pageview', 'screenview', 'event', 'transaction', 'item', 'social', 'exception', 'timing'.

Reference: https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#hitType

**Comment by FloSugar** [comment]
Thank you for you reply!

My purpose is to log Custom Dimensions with a specific object attached - it seems the `ga('send')` is not what I was looking for. 

I can't find proper documentation about logging object using react-ga.

Would using `set` work? 

```
ReactGA.ga(
  'set',
  'openEvent',
  {
  'type': 'eventPreview',
  'userId': this.props.userId, //string
  'invitingId': this.props.invitingId, //string
  })
```

Reference: https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#dimension

**Comment by FloSugar** [comment]
Thank you.
