### ISSUE TITLE
Allow initialize with options

### ISSUE THREAD

**Issue by harryworld** [react-ga/react-ga#30]
I want to use [User ID Feature](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id), which in fact can pass as options in the initialize call

**Comment by adamlofting** [comment]
Thanks, this is a good suggestion, and something I agree we should add.

**Comment by mrsln** [comment]
I'm a little late, but there's a [PR for that] (https://github.com/mozilla/react-ga/pull/28). 
In the meantime you could use [the fork] (https://github.com/mrsln/react-ga).

**Comment by iyoukeyyewei** [comment]
need this feature too.

**Comment by metacortex** [comment]
+1

**Comment by yangshun** [comment]
Can this be merged soon? :smile:

**Comment by yangshun** [comment]
@harryworld sorry this took so long. 1.3.0 has been released and `options` can now be passed into `initialize` and also there's the `ga.set(...)` API for setting of `userId` outside of `initialize`. PR for your reference: https://github.com/react-ga/react-ga/pull/45.

Thanks to @mrsln for the work.

**Comment by amangeot** [comment]
Hello, what's the best way to unset the `userId` ? 

Which value should we put using ReactGA.set({ userId: ... }), `undefined`, `null`, or an empty string ?

`undefined` logs blank when setting `debug` to `true`
