### ISSUE TITLE
Question: Would It Be Possible to Have Non-Dynamic GA Script Loading?

### ISSUE THREAD

**Issue by louisscruz** [react-ga/react-ga#304]
I'm just curious if it would be possible to allow for manual injection of the GA script tag into the html?

It's a very slight performance cost, but the script is requested dynamically (after the JS is loaded). Ideally, I would want to inject the script tag into my HTML at bootstrap time to speed to speed things along.

Would this present problems? Or would it be as simple as adding some kind of check [here](https://github.com/react-ga/react-ga/blob/master/src/utils/loadGA.js#L4)?

**Comment by rockneverdies55** [comment]
Isn't `standardImplementation` option what you're guys talking about?

**Comment by louisscruz** [comment]
That does look like it what I was looking for! Missed that section of the documentation.

Unless that doesn’t actually cover this, this issue can be closed, but I’ll leave that to maintainers as there might be something I’m missing.

**Comment by SimeonC** [comment]
I'll close this, I think `standardImplementation` was added independently by someone else after this ticket and not linked.
