### ISSUE TITLE
Jest mocking results in "Failed to get mock metadata" in 2.5.5

### ISSUE THREAD

**Issue by nerfologist** [react-ga/react-ga#316]
Hello,
I just upgraded from 2.5.3 to 2.5.5 and simply mocking the `react-ga` module using Jest is now failing; running:

```
import ReactGA from 'react-ga';
import './index';

jest.mock('react-ga');

describe('app setup in index.js', () => {
  it('calls ReactGA.initialize()', () => {
    expect(ReactGA.initialize).toBeCalled();
  });
});
```

Results in:
```
 FAIL  src/index.test.js
  ● Test suite failed to run

    Failed to get mock metadata: /Users/nerfologist/proj/myproject/node_modules/react-ga/dist/react-ga.js

    See: https://jestjs.io/docs/manual-mocks.html#content

       9 |   });
      10 | });
    > 11 |
         | ^

      at Runtime._generateMock (node_modules/jest-runtime/build/index.js:747:15)
      at Object.<anonymous> (src/index.test.js:11:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.638s
Ran all test suites matching /index.test.js/i.

Watch Usage: Press w to show more.
```
Do you have an idea of what might be causing this behavior and how to fix it?
Thanks in advance!

**Comment by anajavi** [comment]
I tried your code and it works for me. Using latest jest with Babel 7.

**Comment by nerfologist** [comment]
OK I'll do some more testing from scratch too. Thanks!

**Comment by anajavi** [comment]
Just to be clear, do you have your mock defined in root __mocks__ directory? Because without that jest gives the same error.

**Comment by NicholasAaronBrady** [comment]
@anajavi I believe @nerfologist is in the same boat as me.

To answer your question about having the mock defined in the `__mocks__` directory, the answer is no (at least for me). In _v2.5.3_ it was not necessary to explicitly mock `react-ga`, and now it seems to be?

**Comment by anajavi** [comment]
I managed to get jest mock working by building react-ga umd target with commonjs modules.

Changing
https://github.com/react-ga/react-ga/blob/6dc853170c217fc7d4a7c49e9dbe0938ab013fec/.babelrc#L2

to:
```json
"presets": [["@babel/env", { "modules": "commonjs" }], "@babel/react"]
```
makes jest.mock work again.

I just don't know why it requires build with commonjs..

**Comment by SimeonC** [comment]
Please try v2.5.6 that was just released.

**Comment by NicholasAaronBrady** [comment]
Can confirm v2.5.6 works for me. Really impressive turnaround thank you!

**Comment by nerfologist** [comment]
Works for me too. Thanks a lot!
