### ISSUE TITLE
App crashes after installing npm install react-ga --save

### ISSUE THREAD

**Issue by AkshayBaldia** [react-ga/react-ga#321]
I keep getting this error after installing react-ga... Can't find variable **Document**

![screenshot_2018-12-03-00-22-31_li](https://user-images.githubusercontent.com/26133334/49357140-5303a100-f6f4-11e8-9616-f80b645bef1f.jpg)

**Comment by SimeonC** [comment]
You're building some kind of Cordova app I'm guessing?
I don't remember if anyone's tried this kind of thing before as we really only support web and SSR currently.
Don't know what kind of environment you're running under if "document" isn't defined...

**Comment by AkshayBaldia** [comment]
@SimeonC  I am using React Native. Can I use it without DOM object?

**Comment by SimeonC** [comment]
Not currently. From what I understand using Google analytics in react native requires a considerably different setup. At present we load GA apis via a script element so yes you have to have a DOM.

We’re open to PRs if you can figure out how to do it for react native though.
