### ISSUE TITLE
Can we track url with anchor ?

### ISSUE THREAD

**Issue by kopax** [react-ga/react-ga#330]
I've read this: https://stackoverflow.com/questions/6754982/tracking-hashtags-querystrings-in-ga/6756202#6756202

I am not sure how to setup this through react-ga interface, is that possible ?

Thanks in advance

**Comment by santhosh77h** [comment]
@kopax under options allowAnchor need to be set true but by default it's true maybe its already recording [google ga](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#allowAnchor)

**Comment by kopax** [comment]
Thanks
