### ISSUE TITLE
NPM error:  A rest parameter must be of an array type.

### ISSUE THREAD

**Issue by stephcmartin** [react-ga/react-ga#342]
Haven't had any issues until last night. Wondering if anyone else is receiving the following error from my npm build:

`/home/node/app/node_modules/react-ga/types/index.d.ts
`
`(87,20): A rest parameter must be of an array type.`

So I went to look at the the current types in index.d.ts (line87) is currently:
`export function ga(...args: any): void;`

So I changed it to be an array:
`export function ga([...args]: any): void;`

Managed to get the build running again without any errors.

Possible for you guys to update this bug?

**Comment by archiewald** [comment]
#343 This fixes the issue
