### ISSUE TITLE
Support experiments

### ISSUE THREAD

**Issue by ecesena** [react-ga/react-ga#36]
Any plan to support experiments? Thanks, E.

**Comment by yangshun** [comment]
Hey @ecesena , `react-ga` focuses on supporting the core analytics library and experiments are not a core. As a workaround, v1.3.0 now supports `ga.set(...)` so you can load the experiments framework externally and use `ga.set(...)` to report to Google Analytics which variation was shown to the user.

**Comment by ecesena** [comment]
Sounds good, thank you!

**Comment by alecguintu** [comment]
Can you guys point me in the right direction on how to do this with react and react-ga?

**Comment by ecesena** [comment]
I ended up manually putting the google analytics code for experiments in my index.html.

In google analytics I've set my experiments with different urls, passing the variable exp=a vs exp=b.
For instance, http://example.com/?exp=a vs http://example.com/?exp=b

In the component where I want to implement variations for an experiment, I get the query param and store it as a state variable:

  componentWillMount() {
    var { query } = this.props.location;

    if (query.exp) {
      this.setState({ experiment: query.exp })
    }
  }

Then in the render you can generate what you need based on the value of this.state.experiment.

Hope this helps! E.

**Comment by alecguintu** [comment]
Thanks @ecesena. Same here. But I followed this https://developers.google.com/analytics/solutions/experiments-client-side so I won't need to write query params.

Now I have the script `<script src="//www.google-analytics.com/cx/api.js?experiment=xxx"></script>` in my html and in my componentDidMount have this

```
  componentDidMount() {
    const experimentVariation = cxApi.chooseVariation()
    this.setState({ experimentVariation: experimentVariation })
  }
```

wondering how I would track it afterwards?

I have a method like this

```
  experimentAndRedirect(e) {
    e.preventDefault();

    // ga.set({ 'dimension1': `signup-experiment:${this.state.experimentVariation}` })
    ga.event({ category: 'SignUp Experiment', action: 'Clicked Link', label: `Variation ${this.state.experimentVariation}` })

    browserHistory.push('/sign-up')
  }
```

I added an `ga.event` submit as the article said
>  Experiment data is sent to Google Analytics as parameters attached to other hits, like pageviews, events, or ecommerce transactions. Therefore the variation needs to be chosen before a tracking call is made in order for that value to be sent to Google Analytics.

Am I understand it correctly? Or do I still need to add other things?

Sorry if this becoming a conversation already. I can move it to SO if it get's longer.
