### ISSUE TITLE
Improve `ReactGA.set` documentation

### ISSUE THREAD

**Issue by BrodaNoel** [react-ga/react-ga#363]
Hey guys!
I'm not sure if `ReactGA.set` is used to set a custom dimension, or what.
Could you please guys add more information about when should we use the `set` function?

For example, one of the things that I have to do is defining some dimensions (https://developers.google.com/analytics/devguides/collection/gtagjs/custom-dims-mets), and I'm not sure if I should do it with `.set` function or not. If so, I don't even know how to do it.

For example, in case we have to add a custom dimension, should it be used in this way?:
```
ReactGA.set({ dimension5: some_value });
```

**Comment by iamvishalbisht** [comment]
Hey please someone let me know how to exactly setup custom dimensions in React-ga.
Like there is not a definitive doc which tells me how to initialise the custom dimensions,
please tell us if we have to do it like -
ReactGA.ga('set', 'dimension3', role);
or
ReactGA.set({ dimension3: some_value });
or
ReactGA.initialize(trackingID,{
      gaOptions: {
        dimension3 : role
      }
    });
or
ReactGA.set({"dimension_name": some_value });
