### ISSUE TITLE
Publish 2.6.0 to npm?

### ISSUE THREAD

**Issue by ono** [react-ga/react-ga#367]
2.6.0 was out in March but it hasn't be pushed to npm yet. https://www.npmjs.com/package/react-ga

Any chance you can push it to NPM soon? We'd like to use multiple trackers :pray: Thanks!

**Comment by iam-medvedev** [comment]
Any updates?

**Comment by entruv** [comment]
Did you do regression testing ?

**Comment by SimeonC** [comment]
Should be published now I think? 🤔 

Or at least the v3.0.0 is out anyway.
