### ISSUE TITLE
Tracking page views using ReduxRouter

### ISSUE THREAD

**Issue by Robinnnnn** [react-ga/react-ga#38]
User @craigrich provided a [great solution](https://github.com/mozilla/react-ga/issues/31) for tracking page views by using react-router's built-in `onUpdate` handler.

The issue is I'm using redux-router like so:
```
export const Root = ({
  store
}) => (
  <div>
    <Provider store={store}>
      <div>
        <ReduxRouter>
          {routes}
        </ReduxRouter>
      </div>
    </Provider>
  </div>
)
```
`ReduxRouter` doesn't come with the same onUpdate handler, so I'm wondering how I can track pageviews at this point. Could I somehow use the middleware in my store?

**Comment by craigrich** [comment]
Middleware is the way to go - Try this: 
```
function logPathChange({ getState }) {
  return (next) =>
    (action) => {

      if (action.type == '@@reduxReactRouter/routerDidChange'){
         console.info(`Route Changed: ${action.payload.location.pathname}`);
         ga.pageview(action.payload.location.pathname);
      }
     
      return next(action);

    };
}

const store = compose(
  reduxReactRouter({ createHistory }),
  applyMiddleware(logPathChange)
)(createStore)(reducer);

**Comment by Robinnnnn** [comment]
@craigrich this is beautiful, I appreciate it. 

I'm actually in the midst of migrating over to [redux-simple-router](https://www.npmjs.com/package/redux-simple-router) which makes it much easier to track the user's location. I think this will be a better long-term solution given that [redux-router](https://www.npmjs.com/package/redux-router) still claims to be in an experimental stage.

Nonetheless would you like to post your answer to [my question on s/o](http://stackoverflow.com/questions/35567749/logging-route-changes-in-redux-router/35581581#35581581) so you can win some internet points?

**Comment by rickyPanzer** [comment]
@craigrich thanks so much!!

My version, based off of your code, is slightly different. I'm using a router implementation from https://github.com/erikras/react-redux-universal-hot-example/.

```
function logPathChange({ getState }) {
    return (next) =>
      (action) => {

        if (action.type == '@@router/UPDATE_LOCATION'){
           console.info(`Route Changed: ${action.payload.pathname}`);
           ga.pageview(action.payload.pathname);
        }
        // console.log('hello there');
        console.log(action);

        return next(action);

      };
  }
```

**Comment by yangshun** [comment]
This issue seems resolved. You are welcome to make a PR to add usage examples for the various react-related libraries into the README :smile:
