### ISSUE TITLE
react-ga, NextJS - ERR_UNSAFE_REDIRECT

### ISSUE THREAD

**Issue by ScottAgirs** [react-ga/react-ga#392]
# bug: ERR_UNSAFE_REDIRECT

Followed [this example](https://github.com/zeit/next.js/tree/canary/examples/with-react-ga), and I get the following error in the console:

![image](https://user-images.githubusercontent.com/11737572/67639265-2afccd80-f8c4-11e9-957d-a7b423e21257.png)

PS:
`"next": "^9.1.1",`
And on Analytics dashboard no visits are being recorded

**Comment by pawelotto** [comment]
Same problem here with nextjs 9. react-ga works perfectly on localhost in development mode but fails when online in production.

**Comment by pawelotto** [comment]
I've noticed that this problem occurs when you have some sort of adblock or other privacy enhancing extension enabled. After switching those off problem went away.

**Comment by ScottAgirs** [comment]
@pawelotto this is correct. I can confirm that the issue was identified and occurs, when there are privacy-related blocks in place within browser or laptop.

If anyone reading this is experiencing similar issues, try switching browsers and disabling any ad blockers.
