### ISSUE TITLE
Update to use of autotrack

### ISSUE THREAD

**Issue by pke** [react-ga/react-ga#40]
Google released the Autotrack node module https://github.com/googleanalytics/autotrack
Are there any plans to upgrade this `react-ga` to the Autotrack module?

**Comment by yangshun** [comment]
Hey @pke , `react-ga` already has support for plugins. Install the `autotrack` plugin separately and load the plugin via `ga.plugin.require('autotrack')`.

More documentation can be found here: https://github.com/react-ga/react-ga#gapluginrequirename

**Comment by pke** [comment]
Ah cool. Ok. I rolled out my own solution for now using the GA Universal API. It works except for the event reporting. So maybe I'll give `react-ga` another try later.

**Comment by adrianhorning** [comment]
I'm having trouble getting the maxScrollTracker to work. 
I npm installed autotrack, then put `ReactGA.plugin.require('autotrack');` and `ReactGA.plugin.execute('autotrack', 'maxScrollTracker');` in the page I wanted to track. What am I missing?

**Comment by FinnFrotscher** [comment]
@adrianhorning +1

**Comment by FinnFrotscher** [comment]
```   
   1import React, { FC } from 'react';
   2
   3import ReactGA from 'react-ga';
   4import 'autotrack';
   5
   6import { useUser } from '../user/useUser';
   7
   8export const AnalyticsProvider: FC = ({ children }) => {
   9  const { user } = useUser();
  10
  11  ReactGA.initialize(process.env.GA_ID, {
  12    debug: true,
  13    gaOptions: { userId: user.id },
  14  });
  15
  16  console.log('ReactGA', process.env.GA_ID, ReactGA);
  17
  18  ReactGA.plugin.require('autotrack');
  19
  20  // ReactGA.pageview(window.location.pathname + window.location.search);
  21
  22  return <>{children}</>;
  23};
```
