### ISSUE TITLE
ReactGA not tracking

### ISSUE THREAD

**Issue by BryanKo** [react-ga/react-ga#413]
react-ga does not seem to be tracking. Google Analytics Debugger seems to be tracking the call, but I'm not entirely sure what the send beacon means in the ga('send', ...) call. Am I doing something wrong?

```javascript
import React from 'react';
import ReactGA from 'react-ga';

class App extends React.Component {
  constructor(props) {
    super(props);
    const trackingId = "UA-000000000-1";
    const location = window.location.pathname + window.location.search
    ReactGA.initialize(trackingId);
    ReactGA.pageview(location);
  }

  render() {
    return (
      <div className="app">
        My app...
      </div>
    );
  }
}

export default App;
```
Running command: ga("create", "UA-000000000-1", "auto")
VM583 analytics_debug.js:25 Running command: ga("send", {hitType: "pageview", page: "/"})

**Comment by arpinoda** [comment]
I think your code looks fine. However, I'm having the same issue all of a sudden in certain browsers.

Browsers' **Content Blockers** are preventing loading of _https://www.google-analytics.com/analytics.js_. 

I'm experiencing this in Mobile Safari 12.3 and Firefox 72.0.2 for Mac. See screenshot below
<img width="443" alt="Firefox inspector console" src="https://user-images.githubusercontent.com/6502201/73764858-a5e64780-4741-11ea-81f1-509bf96bde77.png">

**Comment by BryanKo** [comment]
I downloaded Google Tag Assistant Recording and the call is being recorded. Google Analytics seems to not catch the data in the real time report.
