### ISSUE TITLE
Override added 'rel' attribute

### ISSUE THREAD

**Issue by cosmin-serbanescu** [react-ga/react-ga#416]
Hey guys,
May I ask here how could this behaviour be overridden? 
https://github.com/react-ga/react-ga/blob/9bc6754fa36fca5872219603b63f98537ed5dfe6/test/components/OutboundLink.test.jsx#L97

From what I see it's adding automatically a rel="noopener noreferrer" when a target _blank is set but how can I keep only 'noopener' / add maybe 'nofollow' to this type of link?

**Comment by icelord2** [comment]
I also have the same issue. i would like to add **nofollow** to all the links and the **OutboundLink** is overriding all the rel for **target="_blank"**

**Comment by cosmin-serbanescu** [comment]
@SimeonC This is not working in the way I imagined it should work - I'm unable to remove 'noreferrer' more exactly.
Yes, I'm able to add new attributes to the rel tag but cannot remove the default ones. Any workarounds?
