### ISSUE TITLE
Analytics doesn't work

### ISSUE THREAD

**Issue by rixcian** [react-ga/react-ga#422]
Hi,

I set everything like it's in "Usage" section, but analytics still doesn't work. I also set debug option to true and from console I can see, that the requests to google are sending.

Screenshot from console: https://ibb.co/4Fxr5kK
Here is the code: https://ibb.co/bbz9ts3
Analytics settings: https://ibb.co/BK9cxq7

The tagid and settings in google analytics are correct.

**Comment by jdipallo** [comment]
Same for me. This isn't working for me either. For specifics, I am using a local dev Rails server running ngrok with a custom subdomain. My URL in Google Analytics is "XXXX.ngrok.io". In my local browser, I am navigating to "XXXX.ngrok.io" - the react-ga code is being executed and nothing in Realtime->Content

**Comment by devdeer-alex** [comment]
Same here. I'm using react-ga through Gatsby (gatsby-plugin-google-analytics-gdpr) and it's just keeping quit. Testing GA with simple script injection shows, that the tracking id is correct.

**Comment by himat** [comment]
Same problem. Did anyone get it to work?

**Comment by laurax-1981** [comment]
Same issue here, settings as per "Usage" section, console showing correct behaviour, ma GA does not track any activity at all, not even real time users.

**Comment by jlost** [comment]
Same issue.

**Comment by jlost** [comment]
Sorry, false alarm. It's because I'm using Brave.  
![image](https://user-images.githubusercontent.com/11338926/79049872-24ed7580-7bf4-11ea-9144-6ae9770b7eb4.png)

**Comment by PierrickI3** [comment]
Same here, no errors in the debug console, all ad blockers are disabled but still no hits.

**Comment by himat** [comment]
I fixed mine finally by going to the Wiki tab in the github repo and trying a bunch of the examples. I don't understand why those aren't even linked in the readme.

**Comment by jdipallo** [comment]
Wanna laugh/scream? My issue was I was using a Chrome Extension called Disconnect, an Ad Block type of thing and it was not allowing the Google Analytics to go through....Ugggh! So, check it out - if you have any ad blockers enabled.

**Comment by jdipallo** [comment]
Oh, i see Pierrickl13 has already tried this....sorry i missed that.

**Comment by PierrickI3** [comment]
Actually, I just found out that I wasn't tracking pages correctly. On my side, LOCATION_CHANGE is not fired and therefore trackPage() was never called.

**Comment by rixcian** [comment]
It was the same mistake as @jlost describes it. I'm also using Brave browser so all shields was up. My mistake, so I'm closing this issue.

If you have similar issue just try to shut down all of yours ad blockers. It may helps you.

**Comment by hugoh59** [comment]
Does not work for me either, I added 

`ReactGA.initialize('UA-xxxxxxx-1');
  ReactGA.pageview(window.location.pathname + window.location.search);`

in the main component, is there anything else to do?
