### ISSUE TITLE
Does not allow to send email on event

### ISSUE THREAD

**Issue by samuelpetroline** [react-ga/react-ga#427]
ReactGA does not allow to send email on events. 

Is there a reason for this?

https://github.com/react-ga/react-ga/blob/9bc6754fa36fca5872219603b63f98537ed5dfe6/src/utils/format.js#L7-L17

**Comment by wildmolasses** [comment]
https://support.google.com/analytics/answer/6366371?hl=en

**Comment by samuelpetroline** [comment]
Thanks!
