### ISSUE TITLE
Improve documentation about "standard implementation"

### ISSUE THREAD

**Issue by rafaeleyng** [react-ga/react-ga#429]
Hi there

I'm by any means a Analytics connoisseur, but I'm trying to use `react-ga` to implement some fairly basic tracking. Of course I've failed, and reading the docs I've figured it might have something to do with the "standard implementation" thing.

About this, the README currently states:

> `options.standardImplementation` | Boolean. Optional. Defaults to false. Enables loading GA as google expects it. See here for more information

The "See here" links to further down, where it says:

> To enable standard implemention of google analytics...

And says how to enable it, without saying what it actually is and what difference does that make.

My request here is to improve the README in order to clearly state what is the difference between using or not the option `standardImplementation`, and how exactly the default (non-standard) implementation of this lib is different from the standard implementation, and what difference does that make.

**Comment by rawals1974** [comment]
This doesn't solve the issue or really answer @rafaeleyng's question but it may be useful to others who land here from a similar reason. I discovered this link after seeing a "non-standard implementation" warning in Google Tag Assistant Chrome plugin: https://support.google.com/tagassistant/answer/3207128?ref_topic=2947092#nonstandard

**Comment by elliottpost** [comment]
This doesn't solve the issue or really answer @rafaeleyng's question but it may be useful to others who land here from a similar reason. I discovered this link after seeing a "non-standard implementation" warning in Google Tag Assistant Chrome plugin: https://support.google.com/tagassistant/answer/3207128?ref_topic=2947092#nonstandard
