### ISSUE TITLE
Find new maintainers for react-ga

### ISSUE THREAD

**Issue by adamlofting** [react-ga/react-ga#43]
As you've likely noticed, I've not been spending enough time on this package to keep it up to date. 

But it's being [widely used](https://www.npmjs.com/package/react-ga) so I want to stop bottlenecking on the development.

@impronunciable @craigrich @djolaq @liamhubers @vtambourine @mrsln @disnet @disnet @comamitc

As you've all been kind enough to submit PRs to this package, are any of you interested in becoming ongoing maintainers of the project?

--

Or a related note, if you'd be interested in working on Web Analytics at Mozilla, we have an open role at the moment: https://careers.mozilla.org/position/oeNO2fwB

**Comment by vtambourine** [comment]
Yep, I can do it :)

**Comment by impronunciable** [comment]
I can help if you need some

**Comment by adamlofting** [comment]
@vtambourine @impronunciable thanks!

I've moved this project into it's own github organization so that I can make you admins on the project. You should have invites now. 

If anyone else on this thread is interested, let me know here.

**Comment by impronunciable** [comment]
@adamlofting Thank you! I'll just need write access in order to merge prs.

**Comment by adamlofting** [comment]
Write access should be working now :+1:

**Comment by impronunciable** [comment]
It is, thank you!

**Comment by liamhubers** [comment]
I'm interested aswell!

**Comment by impronunciable** [comment]
How to publish new versions to npm?

**Comment by liamhubers** [comment]
I think it's just changing the version in package.json and then run ```npm publish``` ( changing version can be done using by running ```npm version [patch, minor, major]``` )

**Comment by impronunciable** [comment]
@liamhubers yes but I need access to publish to npm

**Comment by yangshun** [comment]
Hi @adamlofting I would like to contribute to this project too and I use react-ga actively as part of my work. May I join?

**Comment by liamhubers** [comment]
@impronunciable oh in that way haha, access probally would be usefull :)

**Comment by adamlofting** [comment]
@impronunciable do you have an account on https://www.npmjs.com ? Let me know your username and I can add you to the collaborators list.

**Comment by impronunciable** [comment]
@adamlofting My username is danzajdband

thanks!

**Comment by gausie** [comment]
@impronunciable let us know when you push v1.3.0 and i'll update a project to use exceptions immediately :P

**Comment by adamlofting** [comment]
@impronunciable you have the power now! :+1:

**Comment by impronunciable** [comment]
@adamlofting thanks!
@gausie I'm reviewing a pr and then doing the 1.3.0 publish

**Comment by impronunciable** [comment]
@gausie v1.3.0 is out on npm. Closing this
