### ISSUE TITLE
addTrackers build failed

### ISSUE THREAD

**Issue by ckarras11** [react-ga/react-ga#433]
Hey,
Looking through the docs I noticed there was a new addTrackers method exposed for adding trackers after GA was initialized.  I attempted to bring it in and use it which failed.  I then looked through the closed PRs and saw it was just merged last week and the build failed.  Just wanted to bring it up in case it was overlooked.  Looking forward to this feature :+1:

**Comment by SimeonC** [comment]
I was waiting for a few other PRs to try do it all in one go. Will release shortly.

**Comment by ckarras11** [comment]
Awesome thank you so much!

**Comment by SimeonC** [comment]
I’m aiming to do it this week, I want to upgrade the deploy, CI and build process to make releasing less of an utter pain.

**Comment by ckarras11** [comment]
Yeah CI can be a pain for sure!  Figured I would close the issue so it wasn't taking up space.  Really appreciate the responses 👍
