### ISSUE TITLE
Warning message on firefox

### ISSUE THREAD

**Issue by astroana** [react-ga/react-ga#459]
I am currently having a warning message on firefox:

`Some cookies are misusing the recommended “SameSite“ attribute`

`Cookie “_ga” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

`Cookie “_gid” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

`Cookie “_gat” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

I disabled AdBlock but warning still show on the console.
how to fix this?

react ver: 16.13.1
react-ga ver: 3.2.0

edited: on chrome it was because of my avira browser safety, I disabled it and the error is gone but in firefox the warning message is still there.

**Comment by primal100** [comment]
Here's the fix:

```javascript
ReactGA.initialize(trackingID, {
            gaOptions: {
                cookieFlags: 'SameSite=None;Secure'
            }
        });
```

Should probably be made the default in ReactGA

**Comment by astroana** [comment]
Thanks it's working, the message is gone now

**Comment by ebertcrn** [comment]
@primal100 can you be more specific about where I can write this code? I'm having the same trouble @astroana

**Comment by astroana** [comment]
> 
> 
> @primal100 can you be more specific about where I can write this code? I'm having the same trouble @astroana

in your Index.js file and replace the trackingID with your google tracking ID

**Comment by primal100** [comment]
> @primal100 can you be more specific about where I can write this code? I'm having the same trouble @astroana

If you followed the readme procedure in ReactGA you should have a ReactGA.initialize line in your code. It's needed for ReactGA to work. You can add gaOptions in there as in my example.

**Comment by davidpmccormick** [comment]
Would setting `cookieFlags: 'SameSite=Lax;'` (and not making the cookie `secure`) also work? Would it be better/worse/indifferrent? As I understand it, the issue arises because Firefox doesn't default to `SameSite=Lax` if `SameSite` isn't set, whereas other browsers do, so doing that would bring Firefox in line with other browsers, only changing the way Firefox handles the cookies.
