### ISSUE TITLE
React GA org logo

### ISSUE THREAD

**Issue by yangshun** [react-ga/react-ga#46]
Since react-ga has become its own organization, it might be nice to give it a logo. I came up with a simple one here, mashing up React's atom logo with Google Analytics background colors. Feel free to use it for the organization's logo. Suggestions and feedback welcome.

![react-ga](https://cloud.githubusercontent.com/assets/1315101/14061054/35f371c4-f3b1-11e5-914c-efa6cc2fac3b.png)

**Comment by yangshun** [comment]
@adamlofting possible to change the org logo to this?

**Comment by adamlofting** [comment]
:+1: :smile:
