### ISSUE TITLE
Measurement ID not supported?

### ISSUE THREAD

**Issue by jeremeheh** [react-ga/react-ga#465]
For some reason google analytics doesnt give tracking ids anymore (not sure tho) only measurement ids.

**Comment by tanishqsh** [comment]
Face an issue. Uninstalled this and used a custom implemented as suggested by Google.

` 
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-KEYT762WX6"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag('js', new Date());

      gtag('config', 'G-KEYXXXXXXX');
    </script>
`

and

` window.gtag('config', 'G-KEYXXXXXXX', { page_title: document.title, page_path: window.location.pathname + window.location.search });
    console.log('Logged entry to ' + window.location);`

Facing an issue with Browser Router but! Still finding solution

**Comment by jeremeheh** [comment]
> Facing the same issue. Uninstalled this and used a custom implementation as suggested by Google.
> 
> Inserted this in **public index.html**
> 
> ```
> 
> <script async src="https://www.googletagmanager.com/gtag/js?id=G-KEYXXXXXX"></script>
> <script>
>       window.dataLayer = window.dataLayer || [];
>       function gtag() {
>         dataLayer.push(arguments);
>       }
>       gtag('js', new Date());
>       gtag('config', 'G-KEYXXXXXXX');
>     </script>
> ```
> 
> and inserting in every component where I want to send the hit in useEffect()
> 
> ```
> window.gtag('config', 'G-KEYXXXXXXX', { page_title: document.title, page_path: window.location.pathname +
> window.location.search }); console.log('Logged entry to ' + window.location);
> ```

Thank you! This worked for me!

**Comment by tslater** [comment]
I'm curious why this is closed? Is it working? It doesn't seem to be working for me.
