### ISSUE TITLE
GA plugin args support

### ISSUE THREAD

**Issue by Bvz2001** [react-ga/react-ga#48]
In [analytics.js documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/command-queue-reference#require) `require` command takes `pluginName` and optionally `pluginOptions`:
`ga('[trackerName.]require', pluginName, [pluginOptions]);`
while [react-ga supports](https://github.com/react-ga/react-ga/blob/master/src/index.js#L306) only `pluginName` :(

Please, add support of optional arguments:
```
    /**
     * require:
     * GA requires a plugin
     * @param name {String} e.g. 'ecommerce' or 'myplugin'
     * @param args {Object} optional e.g {path: '/log', debug: true}
     */
    require: function(name, args) {
      if (typeof ga === 'function') {
        ga('require', name, args);
      }

      if (_debug) {
        log('called ga(\'require\', \'' + name + '\', \'' + JSON.stringify(args) + '\');');
      }
    },
```

Thanks.
Looking forward to your next release ;)

**Comment by yangshun** [comment]
@Bvz2001 seems like you already have the implementation out! Why not try your hand at submitting a PR? This feature is somewhat related to https://github.com/react-ga/react-ga/pull/47. @romanenko perhaps you can consider adding this into your PR?

**Comment by Bvz2001** [comment]
Hi @yangshun
Back to my laptop, added #50.

**Comment by romanenko** [comment]
@yangshun I think this functionality is unrelated to #47. This PR is about options to be added to plugin initialisation. #47 extends usage of plugin action calls.
