### ISSUE TITLE
I see pageview calls in debug but no pages in google analytics and also no analytics data in tag assistant report

### ISSUE THREAD

**Issue by odedvisiblerisk** [react-ga/react-ga#483]
I added react GA to my site according to the guide here, and also added page monitoring.
When I've turned on debug mode I can see this:
![image](https://user-images.githubusercontent.com/78471988/112482031-4d786c00-8d80-11eb-81d3-839731934b62.png)
But when I look at google analytics dashboard I can see only one page and no relevant events:
![image](https://user-images.githubusercontent.com/78471988/112485871-07bda280-8d84-11eb-9be3-972ac41e5918.png)

Also when I check it with Tag assistance I see no analytics data:
![image](https://user-images.githubusercontent.com/78471988/112486158-4ce1d480-8d84-11eb-95a0-42ae683ace2b.png)

Would appreciate any way of solving or debugging this issue, my goal is to create custom events and see page navigation inside my web application.

**Comment by Vivek205** [comment]
@odedvisiblerisk had you got around this issue?

**Comment by odedvisiblerisk** [comment]
you need to add the page to some of the matrics and tell GA to use a URL page instead of page title 

![image](https://user-images.githubusercontent.com/78471988/119806461-e5164a00-beea-11eb-83a9-6867fd522436.png)

**Comment by t-truong-cna** [comment]
I had sent pageview but my react-app can't tracking page load time !
I have a useEffect with deps `pathname`, and tracking pageview but load time of page not send.
![image](https://user-images.githubusercontent.com/64052391/121125381-acfaf980-c850-11eb-8a47-12c1d17cf9b9.png)

@odedvisiblerisk  can u help me?
