### ISSUE TITLE
reportWebVitals Integration

### ISSUE THREAD

**Issue by aress31** [react-ga/react-ga#504]
Amazing lib, makes it super easy and fun to configure all type of events, however, I am not sure how to integrate and send `web core vitals` (https://create-react-app.dev/docs/measuring-performance/) to Google Analytics.

Could you please provide an example in the doc?

**Comment by aress31** [comment]
Amswering myself,:

```js
  React.useEffect(() => {
    ReactGA.pageview(location.pathname + location.search);

    reportWebVitals(({ id, name, value }) =>
      ReactGA.event({
        action: name,
        category: 'Web Vitals',
        label: id,
        nonInteraction: true,
        value: Math.round(
          name === 'CLS' ? value * 1000 : value
        ),
      })
    );
  }, [location.pathname]);
```

**Comment by buddhist-uni** [comment]
Thanks for this! And to future readers: if you're using `react-ga4`, there's no need to round, as GA4 now supports floating point values. :)
