### ISSUE TITLE
React 15 -  Cannot resolve module 'react/lib/Object.assign' 

### ISSUE THREAD

**Issue by andrewmcnamara** [react-ga/react-ga#52]
After upgrading to React 15 am now receiving this error message on npm install

ERROR in ./~/react-ga/src/components/OutboundLink.js
Module not found: Error: Cannot resolve module 'react/lib/Object.assign'

I'm guessing that this has been removed from 15 ?

**Comment by wasabia** [comment]
yes.

https://github.com/react-ga/react-ga/issues/53

**Comment by yangshun** [comment]
Closed via https://github.com/react-ga/react-ga/pull/54
