### ISSUE TITLE
Now that Google is discontinuing Universal Analytics properties... how to use with Google Analytics 4 property?

### ISSUE THREAD

**Issue by openSourcerer9000** [react-ga/react-ga#526]
So... every tutorial on using Google Analytics with React specifies to use Universal Analytics property only. However, Google says:

```
Warning
Universal Analytics properties will stop collecting data starting July 1, 2023. It’s recommended that you create a Google Analytics 4 property instead.
```

So how can I use this library??

**Comment by steverethink** [comment]
you don't. you probably have to switch to react-ga4 package.

**Comment by openSourcerer9000** [comment]
Nice, yes it works,

**Comment by StevenLiao123** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
