### ISSUE TITLE
react 15.0.0 Object.assign is deprecations

### ISSUE THREAD

**Issue by wasabia** [react-ga/react-ga#53]
react 15.0.0
/~/react-ga/src/components/OutboundLink.js
Module not found: Error: Cannot resolve module 'react/lib/Object.assign' in 

https://github.com/facebook/react/pull/6376

**Comment by wasabia** [comment]
https://github.com/react-ga/react-ga/pull/54

**Comment by pascalpp** [comment]
Is anyone working on this? I could submit a PR to change the dependency to use https://www.npmjs.com/package/object-assign, which is what React is using now.

**Comment by pascalpp** [comment]
Anyone waiting on this to be fixed, you can resolve the issue by adding this to the `resolve.alias` section of your webpack config (if you're using webpack):

```
    resolve: {
        alias: {

            // temporary fix for missing require in `react-ga`
            // cf. https://github.com/react-ga/react-ga/issues/53
            'react/lib/Object.assign': 'object-assign',

        },
    },
```

**Comment by simon-lifelike** [comment]
For the future, [stop using internal modules](https://twitter.com/montogeek/status/718473945851236356)

**Comment by yangshun** [comment]
Closed via https://github.com/react-ga/react-ga/pull/54
