### ISSUE TITLE
[Question] : Custom args in ReactGA.events()

### ISSUE THREAD

**Issue by Deveshb15** [react-ga/react-ga#538]
Is it possible to add custom arguments apart from the ones given in the documentation?

also was wondering if its possible to add Objects in these custom arguments?

**Comment by sKopheK** [comment]
i'm also looking for this, namely to achieve something like this: https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtm#view_item_details

**Comment by Deveshb15** [comment]
@sKopheK looks like this package doesn't work with GA4, there's an alternative package react-ga4 please take a look at it:)
