### ISSUE TITLE
issue with webpack and react-ga/dist/react-ga.js

### ISSUE THREAD

**Issue by pascalpp** [react-ga/react-ga#68]
When I `require('react-ga')` in a webpack-bundled app, I get the following warning:

```
WARNING in ./~/react-ga/dist/react-ga.js
Critical dependencies:
1:480-487 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-ga/dist/react-ga.js 1:480-487
```

I'm not sure why webpack is importing the dist version, when react-ga's package.json specifies main:

```
  "main": "src/index.js",
```

But the real problem is that this dist version results in an odd error in the browser:

```
Uncaught TypeError: Cannot read property 'createClass' of undefined
```

That error is triggered by this line:
https://github.com/react-ga/react-ga/blob/master/dist/react-ga.js#L44

```
var React = (typeof window !== "undefined" ? window['React'] : typeof global !== "undefined" ? global['React'] : null);
```

which seems to be making some odd assumptions about how to access React on window or global. Not sure what's going on there, but the result for me is `null` because React isn't exposed as a global in my app.

It's possible that this dist file isn't meant to be used in bundled apps, so maybe the problem is with webpack or my webpack config. Not sure how to suss that out..

As an interim solution, I've added this to the `resolve.alias` section of my webpack config:

```
resolve: {
    alias: {
        // fix for React.createClass bug in react-ga
        'react-ga': 'react-ga/src/index.js',
    }
}
```

Anyone else experiencing this issue?

**Comment by lapint** [comment]
I have this issue as well. I seem to have it with some other react plugins as well. Very difficult to include some into bundled apps.

**Comment by ZubMono** [comment]
Same iisue here
