### ISSUE TITLE
Viewed (not set) for the title

### ISSUE THREAD

**Issue by alecguintu** [react-ga/react-ga#70]
This might not particularly be an issue but can I ask it here.

I have implemented this package via onUpdate on react-router.

```
const logPageView = () => {
  ga.pageview(window.location.pathname);
}

ReactDOM.render(
  <Provider store={store}>
    <Router routes={routes} history={browserHistory} onUpdate={() => {scrollTop(); logPageView()}} />
  </Provider>,
  document.getElementById('app')
);
```

But on a certain page I have, the report always says `Viewed (not set)` (not set for the page title). I think this is because I use [react-document-meta](https://www.npmjs.com/package/react-document-meta) and ajax request and the page is `componentDidMount` I fetch my data from API server, and update the component + document meta based on the data I get (dynamically I think is the term). But that's just one for that page. I know I can do `ga.pageview(window.location.pathname)` when the fetching finishes but then I think I would have two counts of record for the same page visit. How should I approach this?

**Comment by karanjthakkar** [comment]
@alecguintu Unless your page has a default title set in the `head`, it will show `(not set)` since the `pageview` is sent with the current document title which in your case is not set. Only solution I can think of is to use the native ga object and send it along with a `title` since this library does not support adding a title. Also see #64

**Comment by javaguy** [comment]
I'm not familiar with this specific symptom, but ga documentation for SPA's does state that you should set the page value, and not just use pageview, as the latter does not set the page on the tracker.

https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#tracking_virtual_pageviews

> While technically the send command for pageview hits accepts an optional page field as the third parameter, passing the page field that way is not recommend when tracking single page applications. This is because fields passed via the send command are not set on the tracker—they apply to the current hit only. Not updating the tracker will cause problems if your application sends any non-pageview hits (e.g. events or social interactions), as those hits will be associated with whatever page value the tracker had when it was created.

In my case I'm doing the following (disclaimer: I've just been playing with this library the past couple of days, so this hasn't been fully verified):

```
function handleRouterUpdate() {
    // Use the displayName of the last child page, hence I get the name of my components instead of just the path.
    const pagename = this.state.components[this.state.components.length - 1].displayName;
    ga.set({ page: pagename });
    ga.pageview(pagename);
}
```

**Comment by yangshun** [comment]
In fact this library does support adding of title via the following:
```
ReactGA.set( {
  title, '<your title here>'
});
```
 You can add this line of code when the fetching finishes and this should fix the issue you are facing.

@javaguy brought up a good point about doing `ReactGA.set({ page: pagename });` which we did not realize earlier. Have updated it in 5b51df1e66d317c8f18113de04d7c813750e272a. Thanks all!

**Comment by alecguintu** [comment]
@yangshun I just tried that but it's logging incorrectly.

I have implemented `pageView` like on the documentation (https://github.com/react-ga/react-ga#with-npm) and then I added the `ga.set({title: ...})` part after `componentDidMount` and after the ajax has finished fetching the data. What happened was that it set the title for the next page I visited.
