### ISSUE TITLE
Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by jkettmann** [react-ga/react-ga#81]
I get an error in the initialize function in [line 54](https://github.com/react-ga/react-ga/blob/master/src/index.js#L54): Cannot read property 'parentNode' of undefined

Apparently `m = s.getElementsByTagName(o)[0]` is undefined. The odd think is, that when I do `console.log(s.getElementsByTagName(o))` I get an array with length one. But if I do `console.log(s.getElementsByTagName(o)[0])` I get undefined.

What do we need line 54 ` m.parentNode.insertBefore(a, m);` actually for? When I delete it everything seems to work fine.

**Comment by yangshun** [comment]
Unfortunately that's standard google analytics code, where a `<script>` tag is inserted into the `<head>`. Are you messing around with the `<head>` el?

**Comment by yangshun** [comment]
Hence I'm closing this issue as it's unlikely to be a bug in react-ga, more likely to be a bug in your code. Try adding GA normally without using react-ga, and see if it still occurs. Will be happy to reopen if it is indeed a react-ga bug.

For your reference: https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_javascript_tracking_snippet

**Comment by Nishchit14** [comment]
I'm getting this same issue `Cannot read property 'parentNode' of undefined`

What I debug is `script` tag is not creating itself with this code `a = s.createElement(o)`  and when we find the `script` tag by `s.getElementsByTagName(o)[0];` It returns `undefined`

![image](https://user-images.githubusercontent.com/5078921/49685571-54c1d000-fb0b-11e8-8fc8-1fe9d6ed2e41.png)

**Comment by SimeonC** [comment]
Ah, yes that would be a bug - we copy pasted this excerpt from GA which is normally placed in a script tag. hence that's not an issue.
The only way this can happen is if your page has exactly 0 script tags on the page when this runs (not sure how this is possible actually, you need a script tag to run JS in the browser).
Could you provide us with some more information as to what your HTML markup is at the time that tries to run - mostly interested in the existence of script, html, head and body tags.
