### ISSUE TITLE
Issues when used with server rendering

### ISSUE THREAD

**Issue by evivz** [react-ga/react-ga#84]
It make double calls when used with server side rendering. Any easy fix for it?

I used here: http://docstub.com/

**Comment by franckmaurin** [comment]
Why not using a (typeof window !== "undefined") condition before using GA ?

**Comment by bherila** [comment]
It is typical for this type of behavior to be handled by the library. See https://github.com/react-ga/react-ga/pull/149

**Comment by SimeonC** [comment]
#149 is merged.
