### ISSUE TITLE
Is there anyway to included google analytics key from environment variable?

### ISSUE THREAD

**Issue by chaintan17** [react-ga/react-ga#85]
My project have multiple environment, localhost, test and production.
Each environment have own variables.
I want google analytics to only collect the traffic report when it's on production.
I wonder are there anyway to deal with that?

Thank you so much.

**Comment by yangshun** [comment]
This issue is not specific to `react-ga`. You can use webpack's [DefinePlugin(https://webpack.github.io/docs/list-of-plugins.html#defineplugin) or [envify](https://github.com/hughsk/envify) and use the corresponding environment variables in your code, and do something like this:

```
if (process.env.NODE_ENV === "PRODUCTION") {
  ReactGA.initialize('UA-XXXXXX-XX');
}
```

**Comment by chaintan17** [comment]
Thank you!
