### ISSUE TITLE
Use of Google Tag Manager

### ISSUE THREAD

**Issue by khmelevskii** [react-ga/react-ga#88]
Can react-ga be used with Google Tag Manager?

**Comment by yangshun** [comment]
Unfortunately no. GTM creates tags that make calls to analytics libraries (such as GA). ReactGA does exactly that; it is a wrapper around the `ga` library and makes calls internally the `ga` library. 

In this case you should be using one or the other.

**Comment by povtasci** [comment]
Wasn't this changed ? Can't we still use `react-ga` and Tag Manager together ?

**Comment by CharlieIGG** [comment]
> Wasn't this changed ? Can't we still use react-ga and Tag Manager together ?

Can we?

**Comment by mschipperheyn** [comment]
How does the React-ga event module relate to what Google Tag Manager does? Sounds like it's similar

**Comment by gengue** [comment]
We are in 2017, Can't we still use react-ga and Tag Manager together ? Just we need to load and initialize GA by our own...

**Comment by Sahabial** [comment]
we're in 2021 - can we use GA with GTM?
