### ISSUE TITLE
Exception are not logged in

### ISSUE THREAD

**Issue by manodupont** [react-ga/react-ga#90]
I don't see any exceptions in my reporting ...

Can anyone help me with that ?

i send this 👍 

```
[react-ga] called ga('send', fieldObject);
[react-ga] with fieldObject: {"hitType":"exception","exDescription":"{\"code\":\"I0002\",\"params\":{},\"message\":\"I0002\",\"incident\":\"bce3cfd5-Df66-42b0-B4f0-Ae6dac1b7c6a\",\"exchange\":\"358d47d0-7b8f-11e6-9225-128f9da85adb\",\"status\":500}","exFatal":true}
```

nothing is logged.

Thanks a lot.

**Comment by yangshun** [comment]
@manodupont try stringifying your `exDescription` in `fieldObject` first?

**Comment by yangshun** [comment]
Do you still face this issue? @manodupont

**Comment by SimeonC** [comment]
Closed due to inactivity.

**Comment by kaikun213** [comment]
I also do not see any exceptions in the GA-Dashboards.
Configured a custom one as explained here: https://stackoverflow.com/questions/21718481/report-for-exceptions-from-google-analytics-analytics-js-exception-tracking , but the data is empty.

The application does make a network request tho.
Events and pageviews work just as expected. Maybe they changed to declare exceptions as events? (https://developers.google.com/analytics/devguides/collection/gtagjs/exceptions)

Anyone else facing this issue? Or are the exceptions working as expected?

**Comment by eladitzhakian** [comment]
@kaikun213 same here. did you ever solve this issue?

**Comment by morinted** [comment]
I'm also encountering this.
