### ISSUE TITLE
How to use with single page apps with no routes?

### ISSUE THREAD

**Issue by magician11** [react-ga/react-ga#94]
I have an app that renders everything on the one page, and doesn't use react-router currently.

So when using this module, I'll start with this..

```
var ReactGA = require('react-ga');
ReactGA.initialize('UA-000000-01');
```

But then do I need this as well?

```
function logPageView() {
  ReactGA.set({ page: window.location.pathname });
  ReactGA.pageview(window.location.pathname);
}
```

Or just call one/both of the above methods once in the constructor of my React class?

**Comment by yangshun** [comment]
you just need to call `ReactGA.pageview(window.location.pathname);` in `componentDidMount` of your root component.
