### ISSUE TITLE
 ReactGA.initialize window is not defined

### ISSUE THREAD

**Issue by ofirk12** [react-ga/react-ga#98]
when i try to put this code ReactGA.initialize i get this error :
[2]     })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
[2]        ^
[2] [dev:server] ReferenceError: window is not defined

**Comment by yangshun** [comment]
Are you using this in server-side rendering? ReactGA is not supported on the server

**Comment by ofirk12** [comment]
IF I will build it like this its will work ?:
import ReactGA from 'react-ga';
function logPageView() {
    ReactGA.set({ page: window.location.pathname });
    ReactGA.pageview(window.location.pathname);
}

class App extends React.Component {
    componentWillMount(){
        ReactGA.initialize('UA-89673544-1');
    }
  render() {
    return (
      <MainContainer {...this.props}>
        <Sidebar />
        <Header />
        <div id='body'>
          <Grid>
            <Row>
              <Col xs={12}>
                {this.props.children}
              </Col>
            </Row>
          </Grid>
        </div>
        <Footer />
      </MainContainer>
    );
  }
}

const routes2 = (
    <Route>
        <Route path={checkLogin('/')} component={App} onUpdate={logPageView}>
            <IndexRoute component={Home} />
            <Route path={checkLogin('testtest')} component={testtest}  />
        </Route>
        <Route path='*' component={Login} >

        </Route>
    </Route>

);

??

**Comment by joeLloyd** [comment]
do your logPageView like
    function logPageView () {
	if (typeof window !== 'undefined') {
		ReactGA.set({ page: window.location.pathname });
		ReactGA.pageview(window.location.pathname);
	}
    }

put your init func into the client side entry point

**Comment by udayb2014** [comment]
You could also try this [window-or-global](https://www.npmjs.com/package/window-or-global) library. I am also running into the same issue

**Comment by udayb2014** [comment]
@ofirk12 #104 fix worked for me. If the pull request doesn't go through, you can try something similar as a workaround.
